// Package gtk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtk

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// The available modes for [property@Gtk.CellRendererAccel:accel-mode].
type CellRendererAccelMode int

var xCellRendererAccelModeGLibType func() types.GType

func CellRendererAccelModeGLibType() types.GType {
	core.LazyRegister(&xCellRendererAccelModeGLibType, "GTK", "gtk_cell_renderer_accel_mode_get_type", false)
	return xCellRendererAccelModeGLibType()
}

const (

	// GTK accelerators mode
	CellRendererAccelModeGtkValue CellRendererAccelMode = 0
	// Other accelerator mode
	CellRendererAccelModeOtherValue CellRendererAccelMode = 1
)

// Renders a keyboard accelerator in a cell
//
// `GtkCellRendererAccel` displays a keyboard accelerator (i.e. a key
// combination like `Control + a`). If the cell renderer is editable,
// the accelerator can be changed by simply typing the new combination.
type CellRendererAccel struct {
	CellRendererText
}

var xCellRendererAccelGLibType func() types.GType

func CellRendererAccelGLibType() types.GType {
	core.LazyRegister(&xCellRendererAccelGLibType, "GTK", "gtk_cell_renderer_accel_get_type", false)
	return xCellRendererAccelGLibType()
}

func CellRendererAccelNewFromInternalPtr(ptr uintptr) *CellRendererAccel {
	cls := &CellRendererAccel{}
	cls.Ptr = ptr
	return cls
}

var xNewCellRendererAccel func() uintptr

// Creates a new `GtkCellRendererAccel`.
func NewCellRendererAccel() *CellRendererAccel {
	core.LazyRegister(&xNewCellRendererAccel, "GTK", "gtk_cell_renderer_accel_new", false)
	var cls *CellRendererAccel

	cret := xNewCellRendererAccel()

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &CellRendererAccel{}
	cls.Ptr = cret
	return cls
}

func (c *CellRendererAccel) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *CellRendererAccel) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyAccelKey sets the "accel-key" property.
// The keyval of the accelerator.
func (x *CellRendererAccel) SetPropertyAccelKey(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("accel-key", &v)
}

// GetPropertyAccelKey gets the "accel-key" property.
// The keyval of the accelerator.
func (x *CellRendererAccel) GetPropertyAccelKey() uint {
	var v gobject.Value
	x.GetProperty("accel-key", &v)
	return v.GetUint()
}

// SetPropertyKeycode sets the "keycode" property.
// The hardware keycode of the accelerator. Note that the hardware keycode is
// only relevant if the key does not have a keyval. Normally, the keyboard
// configuration should assign keyvals to all keys.
func (x *CellRendererAccel) SetPropertyKeycode(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("keycode", &v)
}

// GetPropertyKeycode gets the "keycode" property.
// The hardware keycode of the accelerator. Note that the hardware keycode is
// only relevant if the key does not have a keyval. Normally, the keyboard
// configuration should assign keyvals to all keys.
func (x *CellRendererAccel) GetPropertyKeycode() uint {
	var v gobject.Value
	x.GetProperty("keycode", &v)
	return v.GetUint()
}

// Gets emitted when the user has removed the accelerator.
func (x *CellRendererAccel) ConnectAccelCleared(cb *func(CellRendererAccel, string)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("gtk.CellRendererAccel.AccelCleared", func(clsPtr uintptr, PathStringVarp string, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(CellRendererAccel, string))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := CellRendererAccel{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, PathStringVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "accel-cleared", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Gets emitted when the user has selected a new accelerator.
func (x *CellRendererAccel) ConnectAccelEdited(cb *func(CellRendererAccel, string, uint, gdk.ModifierType, uint)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("gtk.CellRendererAccel.AccelEdited", func(clsPtr uintptr, PathStringVarp string, AccelKeyVarp uint, AccelModsVarp gdk.ModifierType, HardwareKeycodeVarp uint, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(CellRendererAccel, string, uint, gdk.ModifierType, uint))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := CellRendererAccel{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, PathStringVarp, AccelKeyVarp, AccelModsVarp, HardwareKeycodeVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "accel-edited", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
