// Package gtk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type GestureLongPressClass struct {
	_ structs.HostLayout
}

func (x *GestureLongPressClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func GestureLongPressClassNewFromInternalPtr(ptr uintptr) *GestureLongPressClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*GestureLongPressClass)(rawPtr)
}

// Recognizes long press gestures.
//
// This gesture is also known as “Press and Hold”.
//
// When the timeout is exceeded, the gesture is triggering the
// [signal@Gtk.GestureLongPress::pressed] signal.
//
// If the touchpoint is lifted before the timeout passes, or if
// it drifts too far of the initial press point, the
// [signal@Gtk.GestureLongPress::cancelled] signal will be emitted.
//
// How long the timeout is before the ::pressed signal gets emitted is
// determined by the [property@Gtk.Settings:gtk-long-press-time] setting.
// It can be modified by the [property@Gtk.GestureLongPress:delay-factor]
// property.
type GestureLongPress struct {
	GestureSingle
}

var xGestureLongPressGLibType func() types.GType

func GestureLongPressGLibType() types.GType {
	core.LazyRegister(&xGestureLongPressGLibType, "GTK", "gtk_gesture_long_press_get_type", false)
	return xGestureLongPressGLibType()
}

func GestureLongPressNewFromInternalPtr(ptr uintptr) *GestureLongPress {
	cls := &GestureLongPress{}
	cls.Ptr = ptr
	return cls
}

var xNewGestureLongPress func() uintptr

// Returns a newly created `GtkGesture` that recognizes long presses.
func NewGestureLongPress() *GestureLongPress {
	core.LazyRegister(&xNewGestureLongPress, "GTK", "gtk_gesture_long_press_new", false)
	var cls *GestureLongPress

	cret := xNewGestureLongPress()

	if cret == 0 {
		return nil
	}
	cls = &GestureLongPress{}
	cls.Ptr = cret
	return cls
}

var xGestureLongPressGetDelayFactor func(uintptr) float64

// Returns the delay factor.
func (x *GestureLongPress) GetDelayFactor() float64 {
	core.LazyRegister(&xGestureLongPressGetDelayFactor, "GTK", "gtk_gesture_long_press_get_delay_factor", false)

	cret := xGestureLongPressGetDelayFactor(x.GoPointer())
	return cret
}

var xGestureLongPressSetDelayFactor func(uintptr, float64)

// Applies the given delay factor.
//
// The default long press time will be multiplied by this value.
// Valid values are in the range [0.5..2.0].
func (x *GestureLongPress) SetDelayFactor(DelayFactorVar float64) {
	core.LazyRegister(&xGestureLongPressSetDelayFactor, "GTK", "gtk_gesture_long_press_set_delay_factor", false)

	xGestureLongPressSetDelayFactor(x.GoPointer(), DelayFactorVar)
}

func (c *GestureLongPress) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *GestureLongPress) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyDelayFactor sets the "delay-factor" property.
// Factor by which to modify the default timeout.
func (x *GestureLongPress) SetPropertyDelayFactor(value float64) {
	var v gobject.Value
	v.Init(gobject.TypeDoubleVal)
	v.SetDouble(value)
	x.SetProperty("delay-factor", &v)
}

// GetPropertyDelayFactor gets the "delay-factor" property.
// Factor by which to modify the default timeout.
func (x *GestureLongPress) GetPropertyDelayFactor() float64 {
	var v gobject.Value
	x.GetProperty("delay-factor", &v)
	return v.GetDouble()
}

// Emitted whenever a press moved too far, or was released
// before [signal@Gtk.GestureLongPress::pressed] happened.
func (x *GestureLongPress) ConnectCancelled(cb *func(GestureLongPress)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("gtk.GestureLongPress.Cancelled", func(clsPtr uintptr, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(GestureLongPress))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := GestureLongPress{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "cancelled", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

// Emitted whenever a press goes unmoved/unreleased longer than
// what the GTK defaults tell.
func (x *GestureLongPress) ConnectPressed(cb *func(GestureLongPress, float64, float64)) uint {
	signalData := glib.SaveSignalHandler(cb)
	cbRefPtr := glib.SharedCallback("gtk.GestureLongPress.Pressed", func(clsPtr uintptr, XVarp float64, YVarp float64, signalData uintptr) {
		handler, ok := glib.GetSignalHandler(signalData)
		if !ok {
			return
		}
		cb, ok := handler.(*func(GestureLongPress, float64, float64))
		if !ok || cb == nil || *cb == nil {
			return
		}
		fa := GestureLongPress{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa, XVarp, YVarp)
	})
	handlerID := gobject.SignalConnectDataRaw(x.GoPointer(), "pressed", cbRefPtr, signalData, glib.SignalDestroyNotify(), gobject.GConnectDefaultValue)
	glib.SaveSignalHandlerMapping(handlerID, signalData)
	return handlerID
}

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
