// Package gtk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type PasswordEntryBufferClass struct {
	_ structs.HostLayout

	ParentClass EntryBufferClass
}

func (x *PasswordEntryBufferClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func PasswordEntryBufferClassNewFromInternalPtr(ptr uintptr) *PasswordEntryBufferClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*PasswordEntryBufferClass)(rawPtr)
}

// A `GtkEntryBuffer` that locks the underlying memory to prevent it
// from being swapped to disk.
//
// `GtkPasswordEntry` uses a `GtkPasswordEntryBuffer`.
type PasswordEntryBuffer struct {
	EntryBuffer
}

var xPasswordEntryBufferGLibType func() types.GType

func PasswordEntryBufferGLibType() types.GType {
	core.LazyRegister(&xPasswordEntryBufferGLibType, "GTK", "gtk_password_entry_buffer_get_type", false)
	return xPasswordEntryBufferGLibType()
}

func PasswordEntryBufferNewFromInternalPtr(ptr uintptr) *PasswordEntryBuffer {
	cls := &PasswordEntryBuffer{}
	cls.Ptr = ptr
	return cls
}

var xNewPasswordEntryBuffer func() uintptr

// Creates a new `GtkEntryBuffer` using secure memory allocations.
func NewPasswordEntryBuffer() *PasswordEntryBuffer {
	core.LazyRegister(&xNewPasswordEntryBuffer, "GTK", "gtk_password_entry_buffer_new", false)
	var cls *PasswordEntryBuffer

	cret := xNewPasswordEntryBuffer()

	if cret == 0 {
		return nil
	}
	cls = &PasswordEntryBuffer{}
	cls.Ptr = cret
	return cls
}

func (c *PasswordEntryBuffer) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *PasswordEntryBuffer) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
