// Package gtk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A set of unsigned integers.
//
// Another name for this data structure is “bitmap”.
//
// The current implementation is based on [roaring bitmaps](https://roaringbitmap.org/).
//
// A bitset allows adding a set of integers and provides support for set operations
// like unions, intersections and checks for equality or if a value is contained
// in the set. `GtkBitset` also contains various functions to query metadata about
// the bitset, such as the minimum or maximum values or its size.
//
// The fastest way to iterate values in a bitset is [struct@Gtk.BitsetIter].
//
// The main use case for `GtkBitset` is implementing complex selections for
// [iface@Gtk.SelectionModel].
type Bitset struct {
	_ structs.HostLayout
}

var xBitsetGLibType func() types.GType

func BitsetGLibType() types.GType {
	core.LazyRegister(&xBitsetGLibType, "GTK", "gtk_bitset_get_type", false)
	return xBitsetGLibType()
}

func (x *Bitset) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func BitsetNewFromInternalPtr(ptr uintptr) *Bitset {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*Bitset)(rawPtr)
}

var xNewBitsetEmpty func() uintptr

// Creates a new empty bitset.
func NewBitsetEmpty() *Bitset {
	core.LazyRegister(&xNewBitsetEmpty, "GTK", "gtk_bitset_new_empty", false)

	cret := xNewBitsetEmpty()
	if cret == 0 {
		return nil
	}
	return (*Bitset)(unsafe.Pointer(cret))
}

var xNewBitsetRange func(uint, uint) uintptr

// Creates a bitset with the given range set.
func NewBitsetRange(StartVar uint, NItemsVar uint) *Bitset {
	core.LazyRegister(&xNewBitsetRange, "GTK", "gtk_bitset_new_range", false)

	cret := xNewBitsetRange(StartVar, NItemsVar)
	if cret == 0 {
		return nil
	}
	return (*Bitset)(unsafe.Pointer(cret))
}

var xBitsetAdd func(uintptr, uint) bool

// Adds @value to @self if it wasn't part of it before.
func (x *Bitset) Add(ValueVar uint) bool {
	core.LazyRegister(&xBitsetAdd, "GTK", "gtk_bitset_add", false)

	cret := xBitsetAdd(x.GoPointer(), ValueVar)
	return cret
}

var xBitsetAddRange func(uintptr, uint, uint)

// Adds all values from @start (inclusive) to @start + @n_items
// (exclusive) in @self.
func (x *Bitset) AddRange(StartVar uint, NItemsVar uint) {
	core.LazyRegister(&xBitsetAddRange, "GTK", "gtk_bitset_add_range", false)

	xBitsetAddRange(x.GoPointer(), StartVar, NItemsVar)
}

var xBitsetAddRangeClosed func(uintptr, uint, uint)

// Adds the closed range [@first, @last], so @first, @last and all
// values in between. @first must be smaller than @last.
func (x *Bitset) AddRangeClosed(FirstVar uint, LastVar uint) {
	core.LazyRegister(&xBitsetAddRangeClosed, "GTK", "gtk_bitset_add_range_closed", false)

	xBitsetAddRangeClosed(x.GoPointer(), FirstVar, LastVar)
}

var xBitsetAddRectangle func(uintptr, uint, uint, uint, uint)

// Interprets the values as a 2-dimensional boolean grid with the given @stride
// and inside that grid, adds a rectangle with the given @width and @height.
func (x *Bitset) AddRectangle(StartVar uint, WidthVar uint, HeightVar uint, StrideVar uint) {
	core.LazyRegister(&xBitsetAddRectangle, "GTK", "gtk_bitset_add_rectangle", false)

	xBitsetAddRectangle(x.GoPointer(), StartVar, WidthVar, HeightVar, StrideVar)
}

var xBitsetContains func(uintptr, uint) bool

// Checks if the given @value has been added to @self
func (x *Bitset) Contains(ValueVar uint) bool {
	core.LazyRegister(&xBitsetContains, "GTK", "gtk_bitset_contains", false)

	cret := xBitsetContains(x.GoPointer(), ValueVar)
	return cret
}

var xBitsetCopy func(uintptr) uintptr

// Creates a copy of @self.
func (x *Bitset) Copy() *Bitset {
	core.LazyRegister(&xBitsetCopy, "GTK", "gtk_bitset_copy", false)

	cret := xBitsetCopy(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Bitset)(unsafe.Pointer(cret))
}

var xBitsetDifference func(uintptr, *Bitset)

// Sets @self to be the symmetric difference of @self and @other.
//
// The symmetric difference is set @self to contain all values that
// were either contained in @self or in @other, but not in both.
// This operation is also called an XOR.
//
// It is allowed for @self and @other to be the same bitset. The bitset
// will be emptied in that case.
func (x *Bitset) Difference(OtherVar *Bitset) {
	core.LazyRegister(&xBitsetDifference, "GTK", "gtk_bitset_difference", false)

	xBitsetDifference(x.GoPointer(), OtherVar)
}

var xBitsetEquals func(uintptr, *Bitset) bool

// Returns %TRUE if @self and @other contain the same values.
func (x *Bitset) Equals(OtherVar *Bitset) bool {
	core.LazyRegister(&xBitsetEquals, "GTK", "gtk_bitset_equals", false)

	cret := xBitsetEquals(x.GoPointer(), OtherVar)
	return cret
}

var xBitsetGetMaximum func(uintptr) uint

// Returns the largest value in @self.
//
// If @self is empty, 0 is returned.
func (x *Bitset) GetMaximum() uint {
	core.LazyRegister(&xBitsetGetMaximum, "GTK", "gtk_bitset_get_maximum", false)

	cret := xBitsetGetMaximum(x.GoPointer())
	return cret
}

var xBitsetGetMinimum func(uintptr) uint

// Returns the smallest value in @self.
//
// If @self is empty, `G_MAXUINT` is returned.
func (x *Bitset) GetMinimum() uint {
	core.LazyRegister(&xBitsetGetMinimum, "GTK", "gtk_bitset_get_minimum", false)

	cret := xBitsetGetMinimum(x.GoPointer())
	return cret
}

var xBitsetGetNth func(uintptr, uint) uint

// Returns the value of the @nth item in self.
//
// If @nth is &gt;= the size of @self, 0 is returned.
func (x *Bitset) GetNth(NthVar uint) uint {
	core.LazyRegister(&xBitsetGetNth, "GTK", "gtk_bitset_get_nth", false)

	cret := xBitsetGetNth(x.GoPointer(), NthVar)
	return cret
}

var xBitsetGetSize func(uintptr) uint64

// Gets the number of values that were added to the set.
//
// For example, if the set is empty, 0 is returned.
//
// Note that this function returns a `guint64`, because when all
// values are set, the return value is `G_MAXUINT + 1`. Unless you
// are sure this cannot happen (it can't with `GListModel`), be sure
// to use a 64bit type.
func (x *Bitset) GetSize() uint64 {
	core.LazyRegister(&xBitsetGetSize, "GTK", "gtk_bitset_get_size", false)

	cret := xBitsetGetSize(x.GoPointer())
	return cret
}

var xBitsetGetSizeInRange func(uintptr, uint, uint) uint64

// Gets the number of values that are part of the set from @first to @last
// (inclusive).
//
// Note that this function returns a `guint64`, because when all values are
// set, the return value is `G_MAXUINT + 1`. Unless you are sure this cannot
// happen (it can't with `GListModel`), be sure to use a 64bit type.
func (x *Bitset) GetSizeInRange(FirstVar uint, LastVar uint) uint64 {
	core.LazyRegister(&xBitsetGetSizeInRange, "GTK", "gtk_bitset_get_size_in_range", false)

	cret := xBitsetGetSizeInRange(x.GoPointer(), FirstVar, LastVar)
	return cret
}

var xBitsetIntersect func(uintptr, *Bitset)

// Sets @self to be the intersection of @self and @other.
//
// In other words, remove all values from @self that are not part of @other.
//
// It is allowed for @self and @other to be the same bitset. Nothing will
// happen in that case.
func (x *Bitset) Intersect(OtherVar *Bitset) {
	core.LazyRegister(&xBitsetIntersect, "GTK", "gtk_bitset_intersect", false)

	xBitsetIntersect(x.GoPointer(), OtherVar)
}

var xBitsetIsEmpty func(uintptr) bool

// Check if no value is contained in bitset.
func (x *Bitset) IsEmpty() bool {
	core.LazyRegister(&xBitsetIsEmpty, "GTK", "gtk_bitset_is_empty", false)

	cret := xBitsetIsEmpty(x.GoPointer())
	return cret
}

var xBitsetRef func(uintptr) uintptr

// Acquires a reference on the given `GtkBitset`.
func (x *Bitset) Ref() *Bitset {
	core.LazyRegister(&xBitsetRef, "GTK", "gtk_bitset_ref", false)

	cret := xBitsetRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Bitset)(unsafe.Pointer(cret))
}

var xBitsetRemove func(uintptr, uint) bool

// Removes @value from @self if it was part of it before.
func (x *Bitset) Remove(ValueVar uint) bool {
	core.LazyRegister(&xBitsetRemove, "GTK", "gtk_bitset_remove", false)

	cret := xBitsetRemove(x.GoPointer(), ValueVar)
	return cret
}

var xBitsetRemoveAll func(uintptr)

// Removes all values from the bitset so that it is empty again.
func (x *Bitset) RemoveAll() {
	core.LazyRegister(&xBitsetRemoveAll, "GTK", "gtk_bitset_remove_all", false)

	xBitsetRemoveAll(x.GoPointer())
}

var xBitsetRemoveRange func(uintptr, uint, uint)

// Removes all values from @start (inclusive) to @start + @n_items (exclusive)
// in @self.
func (x *Bitset) RemoveRange(StartVar uint, NItemsVar uint) {
	core.LazyRegister(&xBitsetRemoveRange, "GTK", "gtk_bitset_remove_range", false)

	xBitsetRemoveRange(x.GoPointer(), StartVar, NItemsVar)
}

var xBitsetRemoveRangeClosed func(uintptr, uint, uint)

// Removes the closed range [@first, @last], so @first, @last and all
// values in between. @first must be smaller than @last.
func (x *Bitset) RemoveRangeClosed(FirstVar uint, LastVar uint) {
	core.LazyRegister(&xBitsetRemoveRangeClosed, "GTK", "gtk_bitset_remove_range_closed", false)

	xBitsetRemoveRangeClosed(x.GoPointer(), FirstVar, LastVar)
}

var xBitsetRemoveRectangle func(uintptr, uint, uint, uint, uint)

// Interprets the values as a 2-dimensional boolean grid with the given @stride
// and inside that grid, removes a rectangle with the given @width and @height.
func (x *Bitset) RemoveRectangle(StartVar uint, WidthVar uint, HeightVar uint, StrideVar uint) {
	core.LazyRegister(&xBitsetRemoveRectangle, "GTK", "gtk_bitset_remove_rectangle", false)

	xBitsetRemoveRectangle(x.GoPointer(), StartVar, WidthVar, HeightVar, StrideVar)
}

var xBitsetShiftLeft func(uintptr, uint)

// Shifts all values in @self to the left by @amount.
//
// Values smaller than @amount are discarded.
func (x *Bitset) ShiftLeft(AmountVar uint) {
	core.LazyRegister(&xBitsetShiftLeft, "GTK", "gtk_bitset_shift_left", false)

	xBitsetShiftLeft(x.GoPointer(), AmountVar)
}

var xBitsetShiftRight func(uintptr, uint)

// Shifts all values in @self to the right by @amount.
//
// Values that end up too large to be held in a #guint are discarded.
func (x *Bitset) ShiftRight(AmountVar uint) {
	core.LazyRegister(&xBitsetShiftRight, "GTK", "gtk_bitset_shift_right", false)

	xBitsetShiftRight(x.GoPointer(), AmountVar)
}

var xBitsetSplice func(uintptr, uint, uint, uint)

// This is a support function for `GListModel` handling, by mirroring
// the `GlistModel::items-changed` signal.
//
// First, it "cuts" the values from @position to @removed from
// the bitset. That is, it removes all those values and shifts
// all larger values to the left by @removed places.
//
// Then, it "pastes" new room into the bitset by shifting all values
// larger than @position by @added spaces to the right. This frees
// up space that can then be filled.
func (x *Bitset) Splice(PositionVar uint, RemovedVar uint, AddedVar uint) {
	core.LazyRegister(&xBitsetSplice, "GTK", "gtk_bitset_splice", false)

	xBitsetSplice(x.GoPointer(), PositionVar, RemovedVar, AddedVar)
}

var xBitsetSubtract func(uintptr, *Bitset)

// Sets @self to be the subtraction of @other from @self.
//
// In other words, remove all values from @self that are part of @other.
//
// It is allowed for @self and @other to be the same bitset. The bitset
// will be emptied in that case.
func (x *Bitset) Subtract(OtherVar *Bitset) {
	core.LazyRegister(&xBitsetSubtract, "GTK", "gtk_bitset_subtract", false)

	xBitsetSubtract(x.GoPointer(), OtherVar)
}

var xBitsetUnion func(uintptr, *Bitset)

// Sets @self to be the union of @self and @other.
//
// That is, add all values from @other into @self that weren't part of it.
//
// It is allowed for @self and @other to be the same bitset. Nothing will
// happen in that case.
func (x *Bitset) Union(OtherVar *Bitset) {
	core.LazyRegister(&xBitsetUnion, "GTK", "gtk_bitset_union", false)

	xBitsetUnion(x.GoPointer(), OtherVar)
}

var xBitsetUnref func(uintptr)

// Releases a reference on the given `GtkBitset`.
//
// If the reference was the last, the resources associated to the @self are
// freed.
func (x *Bitset) Unref() {
	core.LazyRegister(&xBitsetUnref, "GTK", "gtk_bitset_unref", false)

	xBitsetUnref(x.GoPointer())
}

// A CSS style change.
type CssStyleChange struct {
	_ structs.HostLayout
}

func (x *CssStyleChange) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func CssStyleChangeNewFromInternalPtr(ptr uintptr) *CssStyleChange {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*CssStyleChange)(rawPtr)
}

// Provides detailed information on how a scroll operation should be performed.
//
// Scrolling functions usually allow passing a `NULL` scroll info which will
// cause the default values to be used and just scroll the element into view.
type ScrollInfo struct {
	_ structs.HostLayout
}

var xScrollInfoGLibType func() types.GType

func ScrollInfoGLibType() types.GType {
	core.LazyRegister(&xScrollInfoGLibType, "GTK", "gtk_scroll_info_get_type", false)
	return xScrollInfoGLibType()
}

func (x *ScrollInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ScrollInfoNewFromInternalPtr(ptr uintptr) *ScrollInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ScrollInfo)(rawPtr)
}

var xNewScrollInfo func() uintptr

// Creates a new scroll info for scrolling an element into view.
func NewScrollInfo() *ScrollInfo {
	core.LazyRegister(&xNewScrollInfo, "GTK", "gtk_scroll_info_new", false)

	cret := xNewScrollInfo()
	if cret == 0 {
		return nil
	}
	return (*ScrollInfo)(unsafe.Pointer(cret))
}

var xScrollInfoGetEnableHorizontal func(uintptr) bool

// Checks if horizontal scrolling is enabled.
func (x *ScrollInfo) GetEnableHorizontal() bool {
	core.LazyRegister(&xScrollInfoGetEnableHorizontal, "GTK", "gtk_scroll_info_get_enable_horizontal", false)

	cret := xScrollInfoGetEnableHorizontal(x.GoPointer())
	return cret
}

var xScrollInfoGetEnableVertical func(uintptr) bool

// Checks if vertical scrolling is enabled.
func (x *ScrollInfo) GetEnableVertical() bool {
	core.LazyRegister(&xScrollInfoGetEnableVertical, "GTK", "gtk_scroll_info_get_enable_vertical", false)

	cret := xScrollInfoGetEnableVertical(x.GoPointer())
	return cret
}

var xScrollInfoRef func(uintptr) uintptr

// Increases the reference count of a `GtkScrollInfo` by one.
func (x *ScrollInfo) Ref() *ScrollInfo {
	core.LazyRegister(&xScrollInfoRef, "GTK", "gtk_scroll_info_ref", false)

	cret := xScrollInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ScrollInfo)(unsafe.Pointer(cret))
}

var xScrollInfoSetEnableHorizontal func(uintptr, bool)

// Turns horizontal scrolling on or off.
func (x *ScrollInfo) SetEnableHorizontal(HorizontalVar bool) {
	core.LazyRegister(&xScrollInfoSetEnableHorizontal, "GTK", "gtk_scroll_info_set_enable_horizontal", false)

	xScrollInfoSetEnableHorizontal(x.GoPointer(), HorizontalVar)
}

var xScrollInfoSetEnableVertical func(uintptr, bool)

// Turns vertical scrolling on or off.
func (x *ScrollInfo) SetEnableVertical(VerticalVar bool) {
	core.LazyRegister(&xScrollInfoSetEnableVertical, "GTK", "gtk_scroll_info_set_enable_vertical", false)

	xScrollInfoSetEnableVertical(x.GoPointer(), VerticalVar)
}

var xScrollInfoUnref func(uintptr)

// Decreases the reference count of a `GtkScrollInfo` by one.
//
// If the resulting reference count is zero, frees the self.
func (x *ScrollInfo) Unref() {
	core.LazyRegister(&xScrollInfoUnref, "GTK", "gtk_scroll_info_unref", false)

	xScrollInfoUnref(x.GoPointer())
}

const (
	// The value used to refer to a guaranteed invalid position
	// in a `GListModel`.
	//
	// This value may be returned from some functions, others may
	// accept it as input. Its interpretation may differ for different
	// functions.
	//
	// Refer to each function's documentation for if this value is
	// allowed and what it does.
	INVALID_LIST_POSITION uint = 4294967295
)

func init() {
	core.SetPackageName("GTK", "gtk4")
	core.SetSharedLibraries("GTK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
