// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/gtk"
)

type CompletionWordsClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass

	Reserved [10]uintptr
}

func (x *CompletionWordsClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func CompletionWordsClassNewFromInternalPtr(ptr uintptr) *CompletionWordsClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*CompletionWordsClass)(rawPtr)
}

// A [iface@CompletionProvider] for the completion of words.
//
// The `GtkSourceCompletionWords` is an example of an implementation of
// the [iface@CompletionProvider] interface. The proposals are words
// appearing in the registered [class@Gtk.TextBuffer]s.
type CompletionWords struct {
	gobject.Object
}

var xCompletionWordsGLibType func() types.GType

func CompletionWordsGLibType() types.GType {
	core.LazyRegister(&xCompletionWordsGLibType, "GTKSOURCE", "gtk_source_completion_words_get_type", true)
	return xCompletionWordsGLibType()
}

func CompletionWordsNewFromInternalPtr(ptr uintptr) *CompletionWords {
	cls := &CompletionWords{}
	cls.Ptr = ptr
	return cls
}

var xNewCompletionWords func(uintptr) uintptr

func NewCompletionWords(TitleVar *string) *CompletionWords {
	core.LazyRegister(&xNewCompletionWords, "GTKSOURCE", "gtk_source_completion_words_new", true)
	var cls *CompletionWords

	TitleVarPtr := core.GStrdupNullable(TitleVar)
	defer core.GFreeNullable(TitleVarPtr)

	cret := xNewCompletionWords(TitleVarPtr)

	if cret == 0 {
		return nil
	}
	cls = &CompletionWords{}
	cls.Ptr = cret
	return cls
}

var xCompletionWordsRegister func(uintptr, uintptr)

// Registers @buffer in the @words provider.
func (x *CompletionWords) Register(BufferVar *gtk.TextBuffer) {
	core.LazyRegister(&xCompletionWordsRegister, "GTKSOURCE", "gtk_source_completion_words_register", true)

	xCompletionWordsRegister(x.GoPointer(), BufferVar.GoPointer())
}

var xCompletionWordsUnregister func(uintptr, uintptr)

// Unregisters @buffer from the @words provider.
func (x *CompletionWords) Unregister(BufferVar *gtk.TextBuffer) {
	core.LazyRegister(&xCompletionWordsUnregister, "GTKSOURCE", "gtk_source_completion_words_unregister", true)

	xCompletionWordsUnregister(x.GoPointer(), BufferVar.GoPointer())
}

func (c *CompletionWords) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *CompletionWords) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyMinimumWordSize sets the "minimum-word-size" property.
func (x *CompletionWords) SetPropertyMinimumWordSize(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("minimum-word-size", &v)
}

// GetPropertyMinimumWordSize gets the "minimum-word-size" property.
func (x *CompletionWords) GetPropertyMinimumWordSize() uint {
	var v gobject.Value
	x.GetProperty("minimum-word-size", &v)
	return v.GetUint()
}

// SetPropertyPriority sets the "priority" property.
func (x *CompletionWords) SetPropertyPriority(value int) {
	var v gobject.Value
	v.Init(gobject.TypeIntVal)
	v.SetInt(value)
	x.SetProperty("priority", &v)
}

// GetPropertyPriority gets the "priority" property.
func (x *CompletionWords) GetPropertyPriority() int {
	var v gobject.Value
	x.GetProperty("priority", &v)
	return v.GetInt()
}

// SetPropertyProposalsBatchSize sets the "proposals-batch-size" property.
func (x *CompletionWords) SetPropertyProposalsBatchSize(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("proposals-batch-size", &v)
}

// GetPropertyProposalsBatchSize gets the "proposals-batch-size" property.
func (x *CompletionWords) GetPropertyProposalsBatchSize() uint {
	var v gobject.Value
	x.GetProperty("proposals-batch-size", &v)
	return v.GetUint()
}

// SetPropertyScanBatchSize sets the "scan-batch-size" property.
func (x *CompletionWords) SetPropertyScanBatchSize(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("scan-batch-size", &v)
}

// GetPropertyScanBatchSize gets the "scan-batch-size" property.
func (x *CompletionWords) GetPropertyScanBatchSize() uint {
	var v gobject.Value
	x.GetProperty("scan-batch-size", &v)
	return v.GetUint()
}

// SetPropertyTitle sets the "title" property.
func (x *CompletionWords) SetPropertyTitle(value string) {
	var v gobject.Value
	v.Init(gobject.TypeStringVal)
	v.SetString(&value)
	x.SetProperty("title", &v)
}

// GetPropertyTitle gets the "title" property.
func (x *CompletionWords) GetPropertyTitle() string {
	var v gobject.Value
	x.GetProperty("title", &v)
	return v.GetString()
}

// This function requests @proposal to be activated by the
// #GtkSourceCompletionProvider.
//
// What the provider does to activate the proposal is specific to that
// provider. Many providers may choose to insert a #GtkSourceSnippet with
// edit points the user may cycle through.
//
// See also: [class@Snippet], [class@SnippetChunk], [method@View.push_snippet]
func (x *CompletionWords) Activate(ContextVar *CompletionContext, ProposalVar CompletionProposal) {
	XGtkSourceCompletionProviderActivate(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
}

// This function requests that the #GtkSourceCompletionProvider prepares
// @cell to display the contents of @proposal.
//
// Based on @cells column type, you may want to display different information.
//
// This allows for columns of information among completion proposals
// resulting in better alignment of similar content (icons, return types,
// method names, and parameter lists).
func (x *CompletionWords) Display(ContextVar *CompletionContext, ProposalVar CompletionProposal, CellVar *CompletionCell) {
	XGtkSourceCompletionProviderDisplay(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), CellVar.GoPointer())
}

// This function should return the priority of @self in @context.
//
// The priority is used to sort groups of completion proposals by
// provider so that higher priority providers results are shown
// above lower priority providers.
//
// Higher value indicates higher priority.
func (x *CompletionWords) GetPriority(ContextVar *CompletionContext) int {
	cret := XGtkSourceCompletionProviderGetPriority(x.GoPointer(), ContextVar.GoPointer())
	return cret
}

// Gets the title of the completion provider, if any.
//
// Currently, titles are not displayed in the completion results, but may be
// at some point in the future when non-%NULL.
func (x *CompletionWords) GetTitle() string {
	cret := XGtkSourceCompletionProviderGetTitle(x.GoPointer())
	return cret
}

// This function is used to determine if a character inserted into the text
// editor should cause a new completion request to be triggered.
//
// An example would be period '.' which might indicate that the user wants
// to complete method or field names of an object.
//
// This method will only trigger when text is inserted into the #GtkTextBuffer
// while the completion list is visible and a proposal is selected. Incremental
// key-presses (like shift, control, or alt) are not triggerable.
func (x *CompletionWords) IsTrigger(IterVar *gtk.TextIter, ChVar uint32) bool {
	cret := XGtkSourceCompletionProviderIsTrigger(x.GoPointer(), IterVar, ChVar)
	return cret
}

// This function is used to determine if a key typed by the user should
// activate @proposal (resulting in committing the text to the editor).
//
// This is useful when using languages where convention may lead to less
// typing by the user. One example may be the use of "." or "-" to expand
// a field access in the C programming language.
func (x *CompletionWords) KeyActivates(ContextVar *CompletionContext, ProposalVar CompletionProposal, KeyvalVar uint, StateVar gdk.ModifierType) bool {
	cret := XGtkSourceCompletionProviderKeyActivates(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), KeyvalVar, StateVar)
	return cret
}

// Providers should return a list of alternates to @proposal or %NULL if
// there are no alternates available.
//
// This can be used by the completion view to allow the user to move laterally
// through similar proposals, such as overrides of methods by the same name.
func (x *CompletionWords) ListAlternates(ContextVar *CompletionContext, ProposalVar CompletionProposal) uintptr {
	cret := XGtkSourceCompletionProviderListAlternates(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
	return cret
}

// Asynchronously requests that the provider populates the completion
// results for @context.
//
// For providers that would like to populate a [iface@Gio.ListModel] while those
// results are displayed to the user,
// [method@CompletionContext.set_proposals_for_provider] may be used
// to reduce latency until the user sees results.
func (x *CompletionWords) PopulateAsync(ContextVar *CompletionContext, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	XGtkSourceCompletionProviderPopulateAsync(x.GoPointer(), ContextVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

// Completes an asynchronous operation to populate a completion provider.
func (x *CompletionWords) PopulateFinish(ResultVar gio.AsyncResult) (*gio.ListModelBase, error) {
	var cls *gio.ListModelBase
	var cerr *glib.Error

	cret := XGtkSourceCompletionProviderPopulateFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.ListModelBase{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr
}

// This function can be used to filter results previously provided to
// the [class@CompletionContext] by the #GtkSourceCompletionProvider.
//
// This can happen as the user types additional text onto the word so
// that previously matched items may be removed from the list instead of
// generating new [iface@Gio.ListModel] of results.
func (x *CompletionWords) Refilter(ContextVar *CompletionContext, ModelVar gio.ListModel) {
	XGtkSourceCompletionProviderRefilter(x.GoPointer(), ContextVar.GoPointer(), ModelVar.GoPointer())
}

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
