// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import "github.com/bnema/puregotk/pkg/core"

const (
	// Like gtk_source_get_major_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MAJOR_VERSION int = 5
	// Like gtk_source_get_micro_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MICRO_VERSION int = 0
	// Like gtk_source_get_minor_version(), but from the headers used at
	// application compile time, rather than from the library linked
	// against at application run time.
	MINOR_VERSION int = 20
)

var xCheckVersion func(uint, uint, uint) bool

// Like GTK_SOURCE_CHECK_VERSION, but the check for gtk_source_check_version is
// at runtime instead of compile time. This is useful for compiling
// against older versions of GtkSourceView, but using features from newer
// versions.
func CheckVersion(MajorVar uint, MinorVar uint, MicroVar uint) bool {
	core.LazyRegister(&xCheckVersion, "GTKSOURCE", "gtk_source_check_version", true)

	cret := xCheckVersion(MajorVar, MinorVar, MicroVar)
	return cret
}

var xGetMajorVersion func() uint

// Returns the major version number of the GtkSourceView library.
// (e.g. in GtkSourceView version 3.20.0 this is 3.)
//
// This function is in the library, so it represents the GtkSourceView library
// your code is running against. Contrast with the #GTK_SOURCE_MAJOR_VERSION
// macro, which represents the major version of the GtkSourceView headers you
// have included when compiling your code.
func GetMajorVersion() uint {
	core.LazyRegister(&xGetMajorVersion, "GTKSOURCE", "gtk_source_get_major_version", true)

	cret := xGetMajorVersion()
	return cret
}

var xGetMicroVersion func() uint

// Returns the micro version number of the GtkSourceView library.
// (e.g. in GtkSourceView version 3.20.0 this is 0.)
//
// This function is in the library, so it represents the GtkSourceView library
// your code is running against. Contrast with the #GTK_SOURCE_MICRO_VERSION
// macro, which represents the micro version of the GtkSourceView headers you
// have included when compiling your code.
func GetMicroVersion() uint {
	core.LazyRegister(&xGetMicroVersion, "GTKSOURCE", "gtk_source_get_micro_version", true)

	cret := xGetMicroVersion()
	return cret
}

var xGetMinorVersion func() uint

// Returns the minor version number of the GtkSourceView library.
// (e.g. in GtkSourceView version 3.20.0 this is 20.)
//
// This function is in the library, so it represents the GtkSourceView library
// your code is running against. Contrast with the #GTK_SOURCE_MINOR_VERSION
// macro, which represents the minor version of the GtkSourceView headers you
// have included when compiling your code.
func GetMinorVersion() uint {
	core.LazyRegister(&xGetMinorVersion, "GTKSOURCE", "gtk_source_get_minor_version", true)

	cret := xGetMinorVersion()
	return cret
}

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
