// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/gtk"
)

type CompletionProviderInterface struct {
	_ structs.HostLayout

	ParentIface uintptr

	xGetTitle uintptr

	xGetPriority uintptr

	xIsTrigger uintptr

	xKeyActivates uintptr

	xPopulate uintptr

	xPopulateAsync uintptr

	xPopulateFinish uintptr

	xRefilter uintptr

	xDisplay uintptr

	xActivate uintptr

	xListAlternates uintptr
}

func (x *CompletionProviderInterface) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func CompletionProviderInterfaceNewFromInternalPtr(ptr uintptr) *CompletionProviderInterface {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*CompletionProviderInterface)(rawPtr)
}

// OverrideGetTitle sets the "get_title" callback function.
func (x *CompletionProviderInterface) OverrideGetTitle(cb func(CompletionProvider) string) {
	if cb == nil {
		x.xGetTitle = 0
	} else {
		x.xGetTitle = purego.NewCallback(func(SelfVarp uintptr) string {
			return cb(&CompletionProviderBase{Ptr: SelfVarp})
		})
	}
}

// GetGetTitle gets the "get_title" callback function.
func (x *CompletionProviderInterface) GetGetTitle() func(CompletionProvider) string {
	if x.xGetTitle == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr) string
	purego.RegisterFunc(&rawCallback, x.xGetTitle)
	return func(SelfVar CompletionProvider) string {
		return rawCallback(SelfVar.GoPointer())
	}
}

// OverrideGetPriority sets the "get_priority" callback function.
func (x *CompletionProviderInterface) OverrideGetPriority(cb func(CompletionProvider, *CompletionContext) int) {
	if cb == nil {
		x.xGetPriority = 0
	} else {
		x.xGetPriority = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr) int {
			return cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp))
		})
	}
}

// GetGetPriority gets the "get_priority" callback function.
func (x *CompletionProviderInterface) GetGetPriority() func(CompletionProvider, *CompletionContext) int {
	if x.xGetPriority == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr) int
	purego.RegisterFunc(&rawCallback, x.xGetPriority)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext) int {
		return rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer())
	}
}

// OverrideIsTrigger sets the "is_trigger" callback function.
func (x *CompletionProviderInterface) OverrideIsTrigger(cb func(CompletionProvider, *gtk.TextIter, uint32) bool) {
	if cb == nil {
		x.xIsTrigger = 0
	} else {
		x.xIsTrigger = purego.NewCallback(func(SelfVarp uintptr, IterVarp *gtk.TextIter, ChVarp uint32) bool {
			return cb(&CompletionProviderBase{Ptr: SelfVarp}, IterVarp, ChVarp)
		})
	}
}

// GetIsTrigger gets the "is_trigger" callback function.
func (x *CompletionProviderInterface) GetIsTrigger() func(CompletionProvider, *gtk.TextIter, uint32) bool {
	if x.xIsTrigger == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, IterVarp *gtk.TextIter, ChVarp uint32) bool
	purego.RegisterFunc(&rawCallback, x.xIsTrigger)
	return func(SelfVar CompletionProvider, IterVar *gtk.TextIter, ChVar uint32) bool {
		return rawCallback(SelfVar.GoPointer(), IterVar, ChVar)
	}
}

// OverrideKeyActivates sets the "key_activates" callback function.
func (x *CompletionProviderInterface) OverrideKeyActivates(cb func(CompletionProvider, *CompletionContext, CompletionProposal, uint, gdk.ModifierType) bool) {
	if cb == nil {
		x.xKeyActivates = 0
	} else {
		x.xKeyActivates = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr, KeyvalVarp uint, StateVarp gdk.ModifierType) bool {
			return cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), &CompletionProposalBase{Ptr: ProposalVarp}, KeyvalVarp, StateVarp)
		})
	}
}

// GetKeyActivates gets the "key_activates" callback function.
func (x *CompletionProviderInterface) GetKeyActivates() func(CompletionProvider, *CompletionContext, CompletionProposal, uint, gdk.ModifierType) bool {
	if x.xKeyActivates == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr, KeyvalVarp uint, StateVarp gdk.ModifierType) bool
	purego.RegisterFunc(&rawCallback, x.xKeyActivates)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, ProposalVar CompletionProposal, KeyvalVar uint, StateVar gdk.ModifierType) bool {
		return rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), KeyvalVar, StateVar)
	}
}

// OverridePopulate sets the "populate" callback function.
func (x *CompletionProviderInterface) OverridePopulate(cb func(CompletionProvider, *CompletionContext) *gio.ListModelBase) {
	if cb == nil {
		x.xPopulate = 0
	} else {
		x.xPopulate = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, cerrp **glib.Error) uintptr {
			ret := cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp))
			if ret == nil {
				return 0
			}
			return ret.GoPointer()
		})
	}
}

// GetPopulate gets the "populate" callback function.
func (x *CompletionProviderInterface) GetPopulate() func(CompletionProvider, *CompletionContext) *gio.ListModelBase {
	if x.xPopulate == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, cerrp **glib.Error) uintptr
	purego.RegisterFunc(&rawCallback, x.xPopulate)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext) *gio.ListModelBase {
		var cerr *glib.Error
		rawRet := rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), &cerr)
		if rawRet == 0 {
			return nil
		}
		ret := &gio.ListModelBase{}
		ret.Ptr = rawRet
		return ret
	}
}

// OverridePopulateAsync sets the "populate_async" callback function.
func (x *CompletionProviderInterface) OverridePopulateAsync(cb func(CompletionProvider, *CompletionContext, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr)) {
	if cb == nil {
		x.xPopulateAsync = 0
	} else {
		x.xPopulateAsync = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
			cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), gio.CancellableNewFromInternalPtr(CancellableVarp), (*gio.AsyncReadyCallback)(unsafe.Pointer(CallbackVarp)), UserDataVarp)
		})
	}
}

// GetPopulateAsync gets the "populate_async" callback function.
func (x *CompletionProviderInterface) GetPopulateAsync() func(CompletionProvider, *CompletionContext, *gio.Cancellable, *gio.AsyncReadyCallback, uintptr) {
	if x.xPopulateAsync == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xPopulateAsync)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
		rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
	}
}

// OverridePopulateFinish sets the "populate_finish" callback function.
func (x *CompletionProviderInterface) OverridePopulateFinish(cb func(CompletionProvider, gio.AsyncResult) *gio.ListModelBase) {
	if cb == nil {
		x.xPopulateFinish = 0
	} else {
		x.xPopulateFinish = purego.NewCallback(func(SelfVarp uintptr, ResultVarp uintptr, cerrp **glib.Error) uintptr {
			ret := cb(&CompletionProviderBase{Ptr: SelfVarp}, &gio.AsyncResultBase{Ptr: ResultVarp})
			if ret == nil {
				return 0
			}
			return ret.GoPointer()
		})
	}
}

// GetPopulateFinish gets the "populate_finish" callback function.
func (x *CompletionProviderInterface) GetPopulateFinish() func(CompletionProvider, gio.AsyncResult) *gio.ListModelBase {
	if x.xPopulateFinish == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ResultVarp uintptr, cerrp **glib.Error) uintptr
	purego.RegisterFunc(&rawCallback, x.xPopulateFinish)
	return func(SelfVar CompletionProvider, ResultVar gio.AsyncResult) *gio.ListModelBase {
		var cerr *glib.Error
		rawRet := rawCallback(SelfVar.GoPointer(), ResultVar.GoPointer(), &cerr)
		if rawRet == 0 {
			return nil
		}
		ret := &gio.ListModelBase{}
		ret.Ptr = rawRet
		return ret
	}
}

// OverrideRefilter sets the "refilter" callback function.
func (x *CompletionProviderInterface) OverrideRefilter(cb func(CompletionProvider, *CompletionContext, gio.ListModel)) {
	if cb == nil {
		x.xRefilter = 0
	} else {
		x.xRefilter = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, ModelVarp uintptr) {
			cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), &gio.ListModelBase{Ptr: ModelVarp})
		})
	}
}

// GetRefilter gets the "refilter" callback function.
func (x *CompletionProviderInterface) GetRefilter() func(CompletionProvider, *CompletionContext, gio.ListModel) {
	if x.xRefilter == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, ModelVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xRefilter)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, ModelVar gio.ListModel) {
		rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), ModelVar.GoPointer())
	}
}

// OverrideDisplay sets the "display" callback function.
func (x *CompletionProviderInterface) OverrideDisplay(cb func(CompletionProvider, *CompletionContext, CompletionProposal, *CompletionCell)) {
	if cb == nil {
		x.xDisplay = 0
	} else {
		x.xDisplay = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr, CellVarp uintptr) {
			cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), &CompletionProposalBase{Ptr: ProposalVarp}, CompletionCellNewFromInternalPtr(CellVarp))
		})
	}
}

// GetDisplay gets the "display" callback function.
func (x *CompletionProviderInterface) GetDisplay() func(CompletionProvider, *CompletionContext, CompletionProposal, *CompletionCell) {
	if x.xDisplay == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr, CellVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xDisplay)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, ProposalVar CompletionProposal, CellVar *CompletionCell) {
		rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), CellVar.GoPointer())
	}
}

// OverrideActivate sets the "activate" callback function.
func (x *CompletionProviderInterface) OverrideActivate(cb func(CompletionProvider, *CompletionContext, CompletionProposal)) {
	if cb == nil {
		x.xActivate = 0
	} else {
		x.xActivate = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr) {
			cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), &CompletionProposalBase{Ptr: ProposalVarp})
		})
	}
}

// GetActivate gets the "activate" callback function.
func (x *CompletionProviderInterface) GetActivate() func(CompletionProvider, *CompletionContext, CompletionProposal) {
	if x.xActivate == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xActivate)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, ProposalVar CompletionProposal) {
		rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
	}
}

// OverrideListAlternates sets the "list_alternates" callback function.
func (x *CompletionProviderInterface) OverrideListAlternates(cb func(CompletionProvider, *CompletionContext, CompletionProposal) uintptr) {
	if cb == nil {
		x.xListAlternates = 0
	} else {
		x.xListAlternates = purego.NewCallback(func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr) uintptr {
			return cb(&CompletionProviderBase{Ptr: SelfVarp}, CompletionContextNewFromInternalPtr(ContextVarp), &CompletionProposalBase{Ptr: ProposalVarp})
		})
	}
}

// GetListAlternates gets the "list_alternates" callback function.
func (x *CompletionProviderInterface) GetListAlternates() func(CompletionProvider, *CompletionContext, CompletionProposal) uintptr {
	if x.xListAlternates == 0 {
		return nil
	}
	var rawCallback func(SelfVarp uintptr, ContextVarp uintptr, ProposalVarp uintptr) uintptr
	purego.RegisterFunc(&rawCallback, x.xListAlternates)
	return func(SelfVar CompletionProvider, ContextVar *CompletionContext, ProposalVar CompletionProposal) uintptr {
		return rawCallback(SelfVar.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
	}
}

// Completion provider interface.
//
// You must implement this interface to provide proposals to [class@Completion].
//
// In most cases, implementations of this interface will want to use
// [vfunc@CompletionProvider.populate_async] to asynchronously populate the results
// to avoid blocking the main loop.
type CompletionProvider interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
	Activate(ContextVar *CompletionContext, ProposalVar CompletionProposal)
	Display(ContextVar *CompletionContext, ProposalVar CompletionProposal, CellVar *CompletionCell)
	GetPriority(ContextVar *CompletionContext) int
	GetTitle() string
	IsTrigger(IterVar *gtk.TextIter, ChVar uint32) bool
	KeyActivates(ContextVar *CompletionContext, ProposalVar CompletionProposal, KeyvalVar uint, StateVar gdk.ModifierType) bool
	ListAlternates(ContextVar *CompletionContext, ProposalVar CompletionProposal) uintptr
	PopulateAsync(ContextVar *CompletionContext, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr)
	PopulateFinish(ResultVar gio.AsyncResult) (*gio.ListModelBase, error)
	Refilter(ContextVar *CompletionContext, ModelVar gio.ListModel)
}

var xCompletionProviderGLibType func() types.GType

func CompletionProviderGLibType() types.GType {
	core.LazyRegister(&xCompletionProviderGLibType, "GTKSOURCE", "gtk_source_completion_provider_get_type", true)
	return xCompletionProviderGLibType()
}

type CompletionProviderBase struct {
	Ptr uintptr
}

func (x *CompletionProviderBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *CompletionProviderBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

// This function requests @proposal to be activated by the
// #GtkSourceCompletionProvider.
//
// What the provider does to activate the proposal is specific to that
// provider. Many providers may choose to insert a #GtkSourceSnippet with
// edit points the user may cycle through.
//
// See also: [class@Snippet], [class@SnippetChunk], [method@View.push_snippet]
func (x *CompletionProviderBase) Activate(ContextVar *CompletionContext, ProposalVar CompletionProposal) {
	XGtkSourceCompletionProviderActivate(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
}

// This function requests that the #GtkSourceCompletionProvider prepares
// @cell to display the contents of @proposal.
//
// Based on @cells column type, you may want to display different information.
//
// This allows for columns of information among completion proposals
// resulting in better alignment of similar content (icons, return types,
// method names, and parameter lists).
func (x *CompletionProviderBase) Display(ContextVar *CompletionContext, ProposalVar CompletionProposal, CellVar *CompletionCell) {
	XGtkSourceCompletionProviderDisplay(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), CellVar.GoPointer())
}

// This function should return the priority of @self in @context.
//
// The priority is used to sort groups of completion proposals by
// provider so that higher priority providers results are shown
// above lower priority providers.
//
// Higher value indicates higher priority.
func (x *CompletionProviderBase) GetPriority(ContextVar *CompletionContext) int {
	cret := XGtkSourceCompletionProviderGetPriority(x.GoPointer(), ContextVar.GoPointer())
	return cret
}

// Gets the title of the completion provider, if any.
//
// Currently, titles are not displayed in the completion results, but may be
// at some point in the future when non-%NULL.
func (x *CompletionProviderBase) GetTitle() string {
	cret := XGtkSourceCompletionProviderGetTitle(x.GoPointer())
	return cret
}

// This function is used to determine if a character inserted into the text
// editor should cause a new completion request to be triggered.
//
// An example would be period '.' which might indicate that the user wants
// to complete method or field names of an object.
//
// This method will only trigger when text is inserted into the #GtkTextBuffer
// while the completion list is visible and a proposal is selected. Incremental
// key-presses (like shift, control, or alt) are not triggerable.
func (x *CompletionProviderBase) IsTrigger(IterVar *gtk.TextIter, ChVar uint32) bool {
	cret := XGtkSourceCompletionProviderIsTrigger(x.GoPointer(), IterVar, ChVar)
	return cret
}

// This function is used to determine if a key typed by the user should
// activate @proposal (resulting in committing the text to the editor).
//
// This is useful when using languages where convention may lead to less
// typing by the user. One example may be the use of "." or "-" to expand
// a field access in the C programming language.
func (x *CompletionProviderBase) KeyActivates(ContextVar *CompletionContext, ProposalVar CompletionProposal, KeyvalVar uint, StateVar gdk.ModifierType) bool {
	cret := XGtkSourceCompletionProviderKeyActivates(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer(), KeyvalVar, StateVar)
	return cret
}

// Providers should return a list of alternates to @proposal or %NULL if
// there are no alternates available.
//
// This can be used by the completion view to allow the user to move laterally
// through similar proposals, such as overrides of methods by the same name.
func (x *CompletionProviderBase) ListAlternates(ContextVar *CompletionContext, ProposalVar CompletionProposal) uintptr {
	cret := XGtkSourceCompletionProviderListAlternates(x.GoPointer(), ContextVar.GoPointer(), ProposalVar.GoPointer())
	return cret
}

// Asynchronously requests that the provider populates the completion
// results for @context.
//
// For providers that would like to populate a [iface@Gio.ListModel] while those
// results are displayed to the user,
// [method@CompletionContext.set_proposals_for_provider] may be used
// to reduce latency until the user sees results.
func (x *CompletionProviderBase) PopulateAsync(ContextVar *CompletionContext, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	XGtkSourceCompletionProviderPopulateAsync(x.GoPointer(), ContextVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

// Completes an asynchronous operation to populate a completion provider.
func (x *CompletionProviderBase) PopulateFinish(ResultVar gio.AsyncResult) (*gio.ListModelBase, error) {
	var cls *gio.ListModelBase
	var cerr *glib.Error

	cret := XGtkSourceCompletionProviderPopulateFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.ListModelBase{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr
}

// This function can be used to filter results previously provided to
// the [class@CompletionContext] by the #GtkSourceCompletionProvider.
//
// This can happen as the user types additional text onto the word so
// that previously matched items may be removed from the list instead of
// generating new [iface@Gio.ListModel] of results.
func (x *CompletionProviderBase) Refilter(ContextVar *CompletionContext, ModelVar gio.ListModel) {
	XGtkSourceCompletionProviderRefilter(x.GoPointer(), ContextVar.GoPointer(), ModelVar.GoPointer())
}

var XGtkSourceCompletionProviderActivate func(uintptr, uintptr, uintptr) = func(instance uintptr, ContextVarp uintptr, ProposalVarp uintptr) {
	core.LazyRegister(&xXGtkSourceCompletionProviderActivate, "GTKSOURCE", "gtk_source_completion_provider_activate", true)
	xXGtkSourceCompletionProviderActivate(instance, ContextVarp, ProposalVarp)
}

var (
	xXGtkSourceCompletionProviderActivate func(uintptr, uintptr, uintptr)
	XGtkSourceCompletionProviderDisplay   func(uintptr, uintptr, uintptr, uintptr) = func(instance uintptr, ContextVarp uintptr, ProposalVarp uintptr, CellVarp uintptr) {
		core.LazyRegister(&xXGtkSourceCompletionProviderDisplay, "GTKSOURCE", "gtk_source_completion_provider_display", true)
		xXGtkSourceCompletionProviderDisplay(instance, ContextVarp, ProposalVarp, CellVarp)
	}
)
var (
	xXGtkSourceCompletionProviderDisplay    func(uintptr, uintptr, uintptr, uintptr)
	XGtkSourceCompletionProviderGetPriority func(uintptr, uintptr) int = func(instance uintptr, ContextVarp uintptr) int {
		core.LazyRegister(&xXGtkSourceCompletionProviderGetPriority, "GTKSOURCE", "gtk_source_completion_provider_get_priority", true)
		return xXGtkSourceCompletionProviderGetPriority(instance, ContextVarp)
	}
)
var (
	xXGtkSourceCompletionProviderGetPriority func(uintptr, uintptr) int
	XGtkSourceCompletionProviderGetTitle     func(uintptr) string = func(instance uintptr) string {
		core.LazyRegister(&xXGtkSourceCompletionProviderGetTitle, "GTKSOURCE", "gtk_source_completion_provider_get_title", true)
		return xXGtkSourceCompletionProviderGetTitle(instance)
	}
)
var (
	xXGtkSourceCompletionProviderGetTitle func(uintptr) string
	XGtkSourceCompletionProviderIsTrigger func(uintptr, *gtk.TextIter, uint32) bool = func(instance uintptr, IterVarp *gtk.TextIter, ChVarp uint32) bool {
		core.LazyRegister(&xXGtkSourceCompletionProviderIsTrigger, "GTKSOURCE", "gtk_source_completion_provider_is_trigger", true)
		return xXGtkSourceCompletionProviderIsTrigger(instance, IterVarp, ChVarp)
	}
)
var (
	xXGtkSourceCompletionProviderIsTrigger   func(uintptr, *gtk.TextIter, uint32) bool
	XGtkSourceCompletionProviderKeyActivates func(uintptr, uintptr, uintptr, uint, gdk.ModifierType) bool = func(instance uintptr, ContextVarp uintptr, ProposalVarp uintptr, KeyvalVarp uint, StateVarp gdk.ModifierType) bool {
		core.LazyRegister(&xXGtkSourceCompletionProviderKeyActivates, "GTKSOURCE", "gtk_source_completion_provider_key_activates", true)
		return xXGtkSourceCompletionProviderKeyActivates(instance, ContextVarp, ProposalVarp, KeyvalVarp, StateVarp)
	}
)
var (
	xXGtkSourceCompletionProviderKeyActivates  func(uintptr, uintptr, uintptr, uint, gdk.ModifierType) bool
	XGtkSourceCompletionProviderListAlternates func(uintptr, uintptr, uintptr) uintptr = func(instance uintptr, ContextVarp uintptr, ProposalVarp uintptr) uintptr {
		core.LazyRegister(&xXGtkSourceCompletionProviderListAlternates, "GTKSOURCE", "gtk_source_completion_provider_list_alternates", true)
		return xXGtkSourceCompletionProviderListAlternates(instance, ContextVarp, ProposalVarp)
	}
)
var (
	xXGtkSourceCompletionProviderListAlternates func(uintptr, uintptr, uintptr) uintptr
	XGtkSourceCompletionProviderPopulateAsync   func(uintptr, uintptr, uintptr, uintptr, uintptr) = func(instance uintptr, ContextVarp uintptr, CancellableVarp uintptr, CallbackVarp uintptr, UserDataVarp uintptr) {
		core.LazyRegister(&xXGtkSourceCompletionProviderPopulateAsync, "GTKSOURCE", "gtk_source_completion_provider_populate_async", true)
		xXGtkSourceCompletionProviderPopulateAsync(instance, ContextVarp, CancellableVarp, CallbackVarp, UserDataVarp)
	}
)
var (
	xXGtkSourceCompletionProviderPopulateAsync func(uintptr, uintptr, uintptr, uintptr, uintptr)
	XGtkSourceCompletionProviderPopulateFinish func(uintptr, uintptr, **glib.Error) uintptr = func(instance uintptr, ResultVarp uintptr, cerrp **glib.Error) uintptr {
		core.LazyRegister(&xXGtkSourceCompletionProviderPopulateFinish, "GTKSOURCE", "gtk_source_completion_provider_populate_finish", true)
		return xXGtkSourceCompletionProviderPopulateFinish(instance, ResultVarp, cerrp)
	}
)
var (
	xXGtkSourceCompletionProviderPopulateFinish func(uintptr, uintptr, **glib.Error) uintptr
	XGtkSourceCompletionProviderRefilter        func(uintptr, uintptr, uintptr) = func(instance uintptr, ContextVarp uintptr, ModelVarp uintptr) {
		core.LazyRegister(&xXGtkSourceCompletionProviderRefilter, "GTKSOURCE", "gtk_source_completion_provider_refilter", true)
		xXGtkSourceCompletionProviderRefilter(instance, ContextVarp, ModelVarp)
	}
)
var xXGtkSourceCompletionProviderRefilter func(uintptr, uintptr, uintptr)

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
