// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gio"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type FileLoaderClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *FileLoaderClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func FileLoaderClassNewFromInternalPtr(ptr uintptr) *FileLoaderClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*FileLoaderClass)(rawPtr)
}

// An error code used with the %GTK_SOURCE_FILE_LOADER_ERROR domain.
type FileLoaderError int

var xFileLoaderErrorGLibType func() types.GType

func FileLoaderErrorGLibType() types.GType {
	core.LazyRegister(&xFileLoaderErrorGLibType, "GTKSOURCE", "gtk_source_file_loader_error_get_type", true)
	return xFileLoaderErrorGLibType()
}

const (

	// The file is too big.
	FileLoaderErrorTooBigValue FileLoaderError = 0
	// It is not
	// possible to detect the encoding automatically.
	FileLoaderErrorEncodingAutoDetectionFailedValue FileLoaderError = 1
	// There was an encoding
	// conversion error and it was needed to use a fallback character.
	FileLoaderErrorConversionFallbackValue FileLoaderError = 2
)

// Load a file into a GtkSourceBuffer.
//
// A `GtkSourceFileLoader` object permits to load the contents of a [iface@Gio.File] or a
// [class@Gio.InputStream] into a [class@Buffer].
//
// A file loader should be used only for one load operation, including errors
// handling. If an error occurs, you can reconfigure the loader and relaunch the
// operation with [method@FileLoader.load_async].
//
// Running a `GtkSourceFileLoader` is an undoable action for the
// [class@Buffer].
//
// After a file loading, the buffer is reset to the contents provided by the
// [iface@Gio.File] or [class@Gio.InputStream], so the buffer is set as “unmodified”, that is,
// [method@Gtk.TextBuffer.set_modified] is called with %FALSE. If the contents isn't
// saved somewhere (for example if you load from stdin), then you should
// probably call [method@Gtk.TextBuffer.set_modified] with %TRUE after calling
// [method@FileLoader.load_finish].
type FileLoader struct {
	gobject.Object
}

var xFileLoaderGLibType func() types.GType

func FileLoaderGLibType() types.GType {
	core.LazyRegister(&xFileLoaderGLibType, "GTKSOURCE", "gtk_source_file_loader_get_type", true)
	return xFileLoaderGLibType()
}

func FileLoaderNewFromInternalPtr(ptr uintptr) *FileLoader {
	cls := &FileLoader{}
	cls.Ptr = ptr
	return cls
}

var xNewFileLoader func(uintptr, uintptr) uintptr

// Creates a new `GtkSourceFileLoader` object. The contents is read from the
// [class@File]'s location.
//
// If not already done, call [method@File.set_location] before calling this constructor.
// The previous location is anyway not needed, because as soon as the file loading begins,
// the @buffer is emptied.
func NewFileLoader(BufferVar *Buffer, FileVar *File) *FileLoader {
	core.LazyRegister(&xNewFileLoader, "GTKSOURCE", "gtk_source_file_loader_new", true)
	var cls *FileLoader

	cret := xNewFileLoader(BufferVar.GoPointer(), FileVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &FileLoader{}
	cls.Ptr = cret
	return cls
}

var xNewFileLoaderFromStream func(uintptr, uintptr, uintptr) uintptr

// Creates a new #GtkSourceFileLoader object. The contents is read from @stream.
func NewFileLoaderFromStream(BufferVar *Buffer, FileVar *File, StreamVar *gio.InputStream) *FileLoader {
	core.LazyRegister(&xNewFileLoaderFromStream, "GTKSOURCE", "gtk_source_file_loader_new_from_stream", true)
	var cls *FileLoader

	cret := xNewFileLoaderFromStream(BufferVar.GoPointer(), FileVar.GoPointer(), StreamVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &FileLoader{}
	cls.Ptr = cret
	return cls
}

var xFileLoaderGetBuffer func(uintptr) uintptr

func (x *FileLoader) GetBuffer() *Buffer {
	core.LazyRegister(&xFileLoaderGetBuffer, "GTKSOURCE", "gtk_source_file_loader_get_buffer", true)
	var cls *Buffer

	cret := xFileLoaderGetBuffer(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Buffer{}
	cls.Ptr = cret
	return cls
}

var xFileLoaderGetCompressionType func(uintptr) CompressionType

func (x *FileLoader) GetCompressionType() CompressionType {
	core.LazyRegister(&xFileLoaderGetCompressionType, "GTKSOURCE", "gtk_source_file_loader_get_compression_type", true)

	cret := xFileLoaderGetCompressionType(x.GoPointer())
	return cret
}

var xFileLoaderGetEncoding func(uintptr) uintptr

func (x *FileLoader) GetEncoding() *Encoding {
	core.LazyRegister(&xFileLoaderGetEncoding, "GTKSOURCE", "gtk_source_file_loader_get_encoding", true)

	cret := xFileLoaderGetEncoding(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Encoding)(unsafe.Pointer(cret))
}

var xFileLoaderGetFile func(uintptr) uintptr

func (x *FileLoader) GetFile() *File {
	core.LazyRegister(&xFileLoaderGetFile, "GTKSOURCE", "gtk_source_file_loader_get_file", true)
	var cls *File

	cret := xFileLoaderGetFile(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &File{}
	cls.Ptr = cret
	return cls
}

var xFileLoaderGetInputStream func(uintptr) uintptr

func (x *FileLoader) GetInputStream() *gio.InputStream {
	core.LazyRegister(&xFileLoaderGetInputStream, "GTKSOURCE", "gtk_source_file_loader_get_input_stream", true)
	var cls *gio.InputStream

	cret := xFileLoaderGetInputStream(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.InputStream{}
	cls.Ptr = cret
	return cls
}

var xFileLoaderGetLocation func(uintptr) uintptr

func (x *FileLoader) GetLocation() *gio.FileBase {
	core.LazyRegister(&xFileLoaderGetLocation, "GTKSOURCE", "gtk_source_file_loader_get_location", true)
	var cls *gio.FileBase

	cret := xFileLoaderGetLocation(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gio.FileBase{}
	cls.Ptr = cret
	return cls
}

var xFileLoaderGetNewlineType func(uintptr) NewlineType

func (x *FileLoader) GetNewlineType() NewlineType {
	core.LazyRegister(&xFileLoaderGetNewlineType, "GTKSOURCE", "gtk_source_file_loader_get_newline_type", true)

	cret := xFileLoaderGetNewlineType(x.GoPointer())
	return cret
}

var xFileLoaderLoadAsync func(uintptr, int, uintptr, uintptr, uintptr, uintptr, uintptr, uintptr)

// Loads asynchronously the file or input stream contents into the [class@Buffer].
//
// See the [iface@Gio.AsyncResult] documentation to know how to use this
// function.
func (x *FileLoader) LoadAsync(IoPriorityVar int, CancellableVar *gio.Cancellable, ProgressCallbackVar *gio.FileProgressCallback, ProgressCallbackDataVar uintptr, ProgressCallbackNotifyVar *glib.DestroyNotify, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {
	core.LazyRegister(&xFileLoaderLoadAsync, "GTKSOURCE", "gtk_source_file_loader_load_async", true)

	xFileLoaderLoadAsync(x.GoPointer(), IoPriorityVar, CancellableVar.GoPointer(), glib.NewCallbackNullable(ProgressCallbackVar), ProgressCallbackDataVar, glib.NewCallbackNullable(ProgressCallbackNotifyVar), glib.NewCallbackNullable(CallbackVar), UserDataVar)
}

var xFileLoaderLoadFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes a file loading started with [method@FileLoader.load_async].
//
// If the contents has been loaded, the following [class@File] properties will
// be updated: the location, the encoding, the newline type and the compression
// type.
func (x *FileLoader) LoadFinish(ResultVar gio.AsyncResult) (bool, error) {
	core.LazyRegister(&xFileLoaderLoadFinish, "GTKSOURCE", "gtk_source_file_loader_load_finish", true)
	var cerr *glib.Error

	cret := xFileLoaderLoadFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr
}

var xFileLoaderSetCandidateEncodings func(uintptr, *glib.SList)

// Sets the candidate encodings for the file loading.
//
// The encodings are tried in the same order as the list.
//
// For convenience, @candidate_encodings can contain duplicates. Only the first
// occurrence of a duplicated encoding is kept in the list.
//
// By default the candidate encodings are (in that order in the list):
//
// 1. If set, the [class@File]'s encoding as returned by [method@File.get_encoding].
// 2. The default candidates as returned by [func@Encoding.get_default_candidates].
func (x *FileLoader) SetCandidateEncodings(CandidateEncodingsVar *glib.SList) {
	core.LazyRegister(&xFileLoaderSetCandidateEncodings, "GTKSOURCE", "gtk_source_file_loader_set_candidate_encodings", true)

	xFileLoaderSetCandidateEncodings(x.GoPointer(), CandidateEncodingsVar)
}

func (c *FileLoader) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *FileLoader) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
