// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type HoverClass struct {
	_ structs.HostLayout

	ParentClass gobject.ObjectClass
}

func (x *HoverClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func HoverClassNewFromInternalPtr(ptr uintptr) *HoverClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*HoverClass)(rawPtr)
}

// Interactive tooltips.
//
// `GtkSourceHover` allows a [class@View] to provide contextual information.
// When enabled, if the user hovers over a word in the text editor, a series
// of registered [iface@HoverProvider] can populate a [class@HoverDisplay]
// with useful information.
//
// To enable call [method@View.get_hover] and add [iface@HoverProvider]
// using [method@Hover.add_provider]. To disable, remove all registered
// providers with [method@Hover.remove_provider].
//
// You can change how long to wait to display the interactive tooltip by
// setting the [property@Hover:hover-delay] property in milliseconds.
type Hover struct {
	gobject.Object
}

var xHoverGLibType func() types.GType

func HoverGLibType() types.GType {
	core.LazyRegister(&xHoverGLibType, "GTKSOURCE", "gtk_source_hover_get_type", true)
	return xHoverGLibType()
}

func HoverNewFromInternalPtr(ptr uintptr) *Hover {
	cls := &Hover{}
	cls.Ptr = ptr
	return cls
}

var xHoverAddProvider func(uintptr, uintptr)

func (x *Hover) AddProvider(ProviderVar HoverProvider) {
	core.LazyRegister(&xHoverAddProvider, "GTKSOURCE", "gtk_source_hover_add_provider", true)

	xHoverAddProvider(x.GoPointer(), ProviderVar.GoPointer())
}

var xHoverRemoveProvider func(uintptr, uintptr)

func (x *Hover) RemoveProvider(ProviderVar HoverProvider) {
	core.LazyRegister(&xHoverRemoveProvider, "GTKSOURCE", "gtk_source_hover_remove_provider", true)

	xHoverRemoveProvider(x.GoPointer(), ProviderVar.GoPointer())
}

func (c *Hover) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *Hover) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// SetPropertyHoverDelay sets the "hover-delay" property.
// Contains the number of milliseconds to delay before showing the hover assistant.
func (x *Hover) SetPropertyHoverDelay(value uint) {
	var v gobject.Value
	v.Init(gobject.TypeUintVal)
	v.SetUint(value)
	x.SetProperty("hover-delay", &v)
}

// GetPropertyHoverDelay gets the "hover-delay" property.
// Contains the number of milliseconds to delay before showing the hover assistant.
func (x *Hover) GetPropertyHoverDelay() uint {
	var v gobject.Value
	x.GetProperty("hover-delay", &v)
	return v.GetUint()
}

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
