// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type StyleSchemeChooserInterface struct {
	_ structs.HostLayout

	BaseInterface uintptr

	xGetStyleScheme uintptr

	xSetStyleScheme uintptr

	Reserved [12]uintptr
}

func (x *StyleSchemeChooserInterface) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func StyleSchemeChooserInterfaceNewFromInternalPtr(ptr uintptr) *StyleSchemeChooserInterface {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*StyleSchemeChooserInterface)(rawPtr)
}

// OverrideGetStyleScheme sets the "get_style_scheme" callback function.
func (x *StyleSchemeChooserInterface) OverrideGetStyleScheme(cb func(StyleSchemeChooser) *StyleScheme) {
	if cb == nil {
		x.xGetStyleScheme = 0
	} else {
		x.xGetStyleScheme = purego.NewCallback(func(ChooserVarp uintptr) uintptr {
			ret := cb(&StyleSchemeChooserBase{Ptr: ChooserVarp})
			if ret == nil {
				return 0
			}
			return ret.GoPointer()
		})
	}
}

// GetGetStyleScheme gets the "get_style_scheme" callback function.
func (x *StyleSchemeChooserInterface) GetGetStyleScheme() func(StyleSchemeChooser) *StyleScheme {
	if x.xGetStyleScheme == 0 {
		return nil
	}
	var rawCallback func(ChooserVarp uintptr) uintptr
	purego.RegisterFunc(&rawCallback, x.xGetStyleScheme)
	return func(ChooserVar StyleSchemeChooser) *StyleScheme {
		rawRet := rawCallback(ChooserVar.GoPointer())
		if rawRet == 0 {
			return nil
		}
		ret := &StyleScheme{}
		ret.Ptr = rawRet
		return ret
	}
}

// OverrideSetStyleScheme sets the "set_style_scheme" callback function.
func (x *StyleSchemeChooserInterface) OverrideSetStyleScheme(cb func(StyleSchemeChooser, *StyleScheme)) {
	if cb == nil {
		x.xSetStyleScheme = 0
	} else {
		x.xSetStyleScheme = purego.NewCallback(func(ChooserVarp uintptr, SchemeVarp uintptr) {
			cb(&StyleSchemeChooserBase{Ptr: ChooserVarp}, StyleSchemeNewFromInternalPtr(SchemeVarp))
		})
	}
}

// GetSetStyleScheme gets the "set_style_scheme" callback function.
func (x *StyleSchemeChooserInterface) GetSetStyleScheme() func(StyleSchemeChooser, *StyleScheme) {
	if x.xSetStyleScheme == 0 {
		return nil
	}
	var rawCallback func(ChooserVarp uintptr, SchemeVarp uintptr)
	purego.RegisterFunc(&rawCallback, x.xSetStyleScheme)
	return func(ChooserVar StyleSchemeChooser, SchemeVar *StyleScheme) {
		rawCallback(ChooserVar.GoPointer(), SchemeVar.GoPointer())
	}
}

// Interface implemented by widgets for choosing style schemes.
//
// `GtkSourceStyleSchemeChooser` is an interface that is implemented by widgets
// for choosing style schemes.
//
// In GtkSourceView, the main widgets that implement this interface are
// [class@StyleSchemeChooserWidget] and [class@StyleSchemeChooserButton].
type StyleSchemeChooser interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
	GetStyleScheme() *StyleScheme
	SetStyleScheme(SchemeVar *StyleScheme)
}

var xStyleSchemeChooserGLibType func() types.GType

func StyleSchemeChooserGLibType() types.GType {
	core.LazyRegister(&xStyleSchemeChooserGLibType, "GTKSOURCE", "gtk_source_style_scheme_chooser_get_type", true)
	return xStyleSchemeChooserGLibType()
}

type StyleSchemeChooserBase struct {
	Ptr uintptr
}

func (x *StyleSchemeChooserBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *StyleSchemeChooserBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

// Gets the currently-selected scheme.
func (x *StyleSchemeChooserBase) GetStyleScheme() *StyleScheme {
	var cls *StyleScheme

	cret := XGtkSourceStyleSchemeChooserGetStyleScheme(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &StyleScheme{}
	cls.Ptr = cret
	return cls
}

// Sets the scheme.
func (x *StyleSchemeChooserBase) SetStyleScheme(SchemeVar *StyleScheme) {
	XGtkSourceStyleSchemeChooserSetStyleScheme(x.GoPointer(), SchemeVar.GoPointer())
}

var XGtkSourceStyleSchemeChooserGetStyleScheme func(uintptr) uintptr = func(instance uintptr) uintptr {
	core.LazyRegister(&xXGtkSourceStyleSchemeChooserGetStyleScheme, "GTKSOURCE", "gtk_source_style_scheme_chooser_get_style_scheme", true)
	return xXGtkSourceStyleSchemeChooserGetStyleScheme(instance)
}

var (
	xXGtkSourceStyleSchemeChooserGetStyleScheme func(uintptr) uintptr
	XGtkSourceStyleSchemeChooserSetStyleScheme  func(uintptr, uintptr) = func(instance uintptr, SchemeVarp uintptr) {
		core.LazyRegister(&xXGtkSourceStyleSchemeChooserSetStyleScheme, "GTKSOURCE", "gtk_source_style_scheme_chooser_set_style_scheme", true)
		xXGtkSourceStyleSchemeChooserSetStyleScheme(instance, SchemeVarp)
	}
)
var xXGtkSourceStyleSchemeChooserSetStyleScheme func(uintptr, uintptr)

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
