// Package gtksource was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gtksource

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/gtk"
)

type StyleSchemeChooserButtonClass struct {
	_ structs.HostLayout

	Parent uintptr

	Reserved [10]uintptr
}

func (x *StyleSchemeChooserButtonClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func StyleSchemeChooserButtonClassNewFromInternalPtr(ptr uintptr) *StyleSchemeChooserButtonClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*StyleSchemeChooserButtonClass)(rawPtr)
}

// A button to launch a style scheme selection dialog.
//
// The `GtkSourceStyleSchemeChooserButton` is a button which displays
// the currently selected style scheme and allows to open a style scheme
// selection dialog to change the style scheme.
// It is suitable widget for selecting a style scheme in a preference dialog.
//
// In `GtkSourceStyleSchemeChooserButton`, a [class@StyleSchemeChooserWidget]
// is used to provide a dialog for selecting style schemes.
type StyleSchemeChooserButton struct {
	gtk.Button
}

var xStyleSchemeChooserButtonGLibType func() types.GType

func StyleSchemeChooserButtonGLibType() types.GType {
	core.LazyRegister(&xStyleSchemeChooserButtonGLibType, "GTKSOURCE", "gtk_source_style_scheme_chooser_button_get_type", true)
	return xStyleSchemeChooserButtonGLibType()
}

func StyleSchemeChooserButtonNewFromInternalPtr(ptr uintptr) *StyleSchemeChooserButton {
	cls := &StyleSchemeChooserButton{}
	cls.Ptr = ptr
	return cls
}

var xNewStyleSchemeChooserButton func() uintptr

// Creates a new #GtkSourceStyleSchemeChooserButton.
func NewStyleSchemeChooserButton() *StyleSchemeChooserButton {
	core.LazyRegister(&xNewStyleSchemeChooserButton, "GTKSOURCE", "gtk_source_style_scheme_chooser_button_new", true)
	var cls *StyleSchemeChooserButton

	cret := xNewStyleSchemeChooserButton()

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &StyleSchemeChooserButton{}
	cls.Ptr = cret
	return cls
}

func (c *StyleSchemeChooserButton) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *StyleSchemeChooserButton) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Requests the user's screen reader to announce the given message.
//
// This kind of notification is useful for messages that
// either have only a visual representation or that are not
// exposed visually at all, e.g. a notification about a
// successful operation.
//
// Also, by using this API, you can ensure that the message
// does not interrupts the user's current screen reader output.
func (x *StyleSchemeChooserButton) Announce(MessageVar string, PriorityVar gtk.AccessibleAnnouncementPriority) {
	gtk.XGtkAccessibleAnnounce(x.GoPointer(), MessageVar, PriorityVar)
}

// Retrieves the accessible identifier for the accessible object.
//
// This functionality can be overridden by `GtkAccessible`
// implementations.
//
// It is left to the accessible implementation to define the scope
// and uniqueness of the identifier.
func (x *StyleSchemeChooserButton) GetAccessibleId() string {
	cret := gtk.XGtkAccessibleGetAccessibleId(x.GoPointer())
	return cret
}

// Retrieves the accessible parent for an accessible object.
//
// This function returns `NULL` for top level widgets.
func (x *StyleSchemeChooserButton) GetAccessibleParent() *gtk.AccessibleBase {
	var cls *gtk.AccessibleBase

	cret := gtk.XGtkAccessibleGetAccessibleParent(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gtk.AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the accessible role of an accessible object.
func (x *StyleSchemeChooserButton) GetAccessibleRole() gtk.AccessibleRole {
	cret := gtk.XGtkAccessibleGetAccessibleRole(x.GoPointer())
	return cret
}

// Retrieves the implementation for the given accessible object.
func (x *StyleSchemeChooserButton) GetAtContext() *gtk.ATContext {
	var cls *gtk.ATContext

	cret := gtk.XGtkAccessibleGetAtContext(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gtk.ATContext{}
	cls.Ptr = cret
	return cls
}

// Queries the coordinates and dimensions of this accessible
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get the bounds from an ignored
// child widget.
func (x *StyleSchemeChooserButton) GetBounds(XVar *int, YVar *int, WidthVar *int, HeightVar *int) bool {
	cret := gtk.XGtkAccessibleGetBounds(x.GoPointer(), XVar, YVar, WidthVar, HeightVar)
	return cret
}

// Retrieves the first accessible child of an accessible object.
func (x *StyleSchemeChooserButton) GetFirstAccessibleChild() *gtk.AccessibleBase {
	var cls *gtk.AccessibleBase

	cret := gtk.XGtkAccessibleGetFirstAccessibleChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gtk.AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the next accessible sibling of an accessible object
func (x *StyleSchemeChooserButton) GetNextAccessibleSibling() *gtk.AccessibleBase {
	var cls *gtk.AccessibleBase

	cret := gtk.XGtkAccessibleGetNextAccessibleSibling(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &gtk.AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Queries a platform state, such as focus.
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get platform state from an ignored
// child widget, as is the case for `GtkText` wrappers.
func (x *StyleSchemeChooserButton) GetPlatformState(StateVar gtk.AccessiblePlatformState) bool {
	cret := gtk.XGtkAccessibleGetPlatformState(x.GoPointer(), StateVar)
	return cret
}

// Resets the accessible property to its default value.
func (x *StyleSchemeChooserButton) ResetProperty(PropertyVar gtk.AccessibleProperty) {
	gtk.XGtkAccessibleResetProperty(x.GoPointer(), PropertyVar)
}

// Resets the accessible relation to its default value.
func (x *StyleSchemeChooserButton) ResetRelation(RelationVar gtk.AccessibleRelation) {
	gtk.XGtkAccessibleResetRelation(x.GoPointer(), RelationVar)
}

// Resets the accessible state to its default value.
func (x *StyleSchemeChooserButton) ResetState(StateVar gtk.AccessibleState) {
	gtk.XGtkAccessibleResetState(x.GoPointer(), StateVar)
}

// Sets the parent and sibling of an accessible object.
//
// This function is meant to be used by accessible implementations that are
// not part of the widget hierarchy, and but act as a logical bridge between
// widgets. For instance, if a widget creates an object that holds metadata
// for each child, and you want that object to implement the `GtkAccessible`
// interface, you will use this function to ensure that the parent of each
// child widget is the metadata object, and the parent of each metadata
// object is the container widget.
func (x *StyleSchemeChooserButton) SetAccessibleParent(ParentVar gtk.Accessible, NextSiblingVar gtk.Accessible) {
	gtk.XGtkAccessibleSetAccessibleParent(x.GoPointer(), ParentVar.GoPointer(), NextSiblingVar.GoPointer())
}

// Updates the next accessible sibling.
//
// That might be useful when a new child of a custom accessible
// is created, and it needs to be linked to a previous child.
func (x *StyleSchemeChooserButton) UpdateNextAccessibleSibling(NewSiblingVar gtk.Accessible) {
	gtk.XGtkAccessibleUpdateNextAccessibleSibling(x.GoPointer(), NewSiblingVar.GoPointer())
}

// Informs ATs that the platform state has changed.
//
// This function should be used by `GtkAccessible` implementations that
// have a platform state but are not widgets. Widgets handle platform
// states automatically.
func (x *StyleSchemeChooserButton) UpdatePlatformState(StateVar gtk.AccessiblePlatformState) {
	gtk.XGtkAccessibleUpdatePlatformState(x.GoPointer(), StateVar)
}

// Updates a list of accessible properties.
//
// See the [enum@Gtk.AccessibleProperty] documentation for the
// value types of accessible properties.
//
// This function should be called by `GtkWidget` types whenever
// an accessible property change must be communicated to assistive
// technologies.
//
// Example:
// ```c
// value = gtk_adjustment_get_value (adjustment);
// gtk_accessible_update_property (GTK_ACCESSIBLE (spin_button),
//
//	GTK_ACCESSIBLE_PROPERTY_VALUE_NOW, value,
//	-1);
//
// ```
func (x *StyleSchemeChooserButton) UpdateProperty(FirstPropertyVar gtk.AccessibleProperty, varArgs ...interface{}) {
	gtk.XGtkAccessibleUpdateProperty(x.GoPointer(), FirstPropertyVar, varArgs...)
}

// Updates an array of accessible properties.
//
// This function should be called by `GtkWidget` types whenever an accessible
// property change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *StyleSchemeChooserButton) UpdatePropertyValue(NPropertiesVar int, PropertiesVar []gtk.AccessibleProperty, ValuesVar []gobject.Value) {
	gtk.XGtkAccessibleUpdatePropertyValue(x.GoPointer(), NPropertiesVar, PropertiesVar, ValuesVar)
}

// Updates a list of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// If the [enum@Gtk.AccessibleRelation] requires a list of references,
// you should pass each reference individually, followed by `NULL`, e.g.
//
// ```c
// gtk_accessible_update_relation (accessible,
//
//	GTK_ACCESSIBLE_RELATION_CONTROLS,
//	  ref1, NULL,
//	GTK_ACCESSIBLE_RELATION_LABELLED_BY,
//	  ref1, ref2, ref3, NULL,
//	-1);
//
// ```
func (x *StyleSchemeChooserButton) UpdateRelation(FirstRelationVar gtk.AccessibleRelation, varArgs ...interface{}) {
	gtk.XGtkAccessibleUpdateRelation(x.GoPointer(), FirstRelationVar, varArgs...)
}

// Updates an array of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *StyleSchemeChooserButton) UpdateRelationValue(NRelationsVar int, RelationsVar []gtk.AccessibleRelation, ValuesVar []gobject.Value) {
	gtk.XGtkAccessibleUpdateRelationValue(x.GoPointer(), NRelationsVar, RelationsVar, ValuesVar)
}

// Updates a list of accessible states.
//
// See the [enum@Gtk.AccessibleState] documentation for the
// value types of accessible states.
//
// This function should be called by `GtkWidget` types whenever
// an accessible state change must be communicated to assistive
// technologies.
//
// Example:
//
// ```c
// value = GTK_ACCESSIBLE_TRISTATE_MIXED;
// gtk_accessible_update_state (GTK_ACCESSIBLE (check_button),
//
//	GTK_ACCESSIBLE_STATE_CHECKED, value,
//	-1);
//
// ```
func (x *StyleSchemeChooserButton) UpdateState(FirstStateVar gtk.AccessibleState, varArgs ...interface{}) {
	gtk.XGtkAccessibleUpdateState(x.GoPointer(), FirstStateVar, varArgs...)
}

// Updates an array of accessible states.
//
// This function should be called by `GtkWidget` types whenever an accessible
// state change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *StyleSchemeChooserButton) UpdateStateValue(NStatesVar int, StatesVar []gtk.AccessibleState, ValuesVar []gobject.Value) {
	gtk.XGtkAccessibleUpdateStateValue(x.GoPointer(), NStatesVar, StatesVar, ValuesVar)
}

// Gets the action name for @actionable.
func (x *StyleSchemeChooserButton) GetActionName() string {
	cret := gtk.XGtkActionableGetActionName(x.GoPointer())
	return cret
}

// Gets the current target value of @actionable.
func (x *StyleSchemeChooserButton) GetActionTargetValue() *glib.Variant {
	cret := gtk.XGtkActionableGetActionTargetValue(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.Variant)(unsafe.Pointer(cret))
}

// Specifies the name of the action with which this widget should be
// associated.
//
// If @action_name is %NULL then the widget will be unassociated from
// any previous action.
//
// Usually this function is used when the widget is located (or will be
// located) within the hierarchy of a `GtkApplicationWindow`.
//
// Names are of the form “win.save” or “app.quit” for actions on the
// containing [class@ApplicationWindow] or its associated [class@Application],
// respectively. This is the same form used for actions in the [class@Gio.Menu]
// associated with the window.
func (x *StyleSchemeChooserButton) SetActionName(ActionNameVar *string) {
	ActionNameVarPtr := core.GStrdupNullable(ActionNameVar)
	defer core.GFreeNullable(ActionNameVarPtr)

	gtk.XGtkActionableSetActionName(x.GoPointer(), ActionNameVarPtr)
}

// Sets the target of an actionable widget.
//
// This is a convenience function that calls [ctor@GLib.Variant.new] for
// @format_string and uses the result to call
// [method@Gtk.Actionable.set_action_target_value].
//
// If you are setting a string-valued target and want to set
// the action name at the same time, you can use
// [method@Gtk.Actionable.set_detailed_action_name].
func (x *StyleSchemeChooserButton) SetActionTarget(FormatStringVar string, varArgs ...interface{}) {
	gtk.XGtkActionableSetActionTarget(x.GoPointer(), FormatStringVar, varArgs...)
}

// Sets the target value of an actionable widget.
//
// If @target_value is %NULL then the target value is unset.
//
// The target value has two purposes. First, it is used as the parameter
// to activation of the action associated with the `GtkActionable` widget.
// Second, it is used to determine if the widget should be rendered as
// “active” — the widget is active if the state is equal to the given target.
//
// Consider the example of associating a set of buttons with a [iface@Gio.Action]
// with string state in a typical “radio button” situation. Each button
// will be associated with the same action, but with a different target
// value for that action. Clicking on a particular button will activate
// the action with the target of that button, which will typically cause
// the action’s state to change to that value. Since the action’s state
// is now equal to the target value of the button, the button will now
// be rendered as active (and the other buttons, with different targets,
// rendered inactive).
func (x *StyleSchemeChooserButton) SetActionTargetValue(TargetValueVar *glib.Variant) {
	gtk.XGtkActionableSetActionTargetValue(x.GoPointer(), TargetValueVar)
}

// Sets the action-name and associated string target value of an
// actionable widget.
//
// @detailed_action_name is a string in the format accepted by
// [func@Gio.Action.parse_detailed_name].
func (x *StyleSchemeChooserButton) SetDetailedActionName(DetailedActionNameVar string) {
	gtk.XGtkActionableSetDetailedActionName(x.GoPointer(), DetailedActionNameVar)
}

// Gets the ID of the @buildable object.
//
// `GtkBuilder` sets the name based on the ID attribute
// of the `&lt;object&gt;` tag used to construct the @buildable.
func (x *StyleSchemeChooserButton) GetBuildableId() string {
	cret := gtk.XGtkBuildableGetBuildableId(x.GoPointer())
	return cret
}

// Gets the currently-selected scheme.
func (x *StyleSchemeChooserButton) GetStyleScheme() *StyleScheme {
	var cls *StyleScheme

	cret := XGtkSourceStyleSchemeChooserGetStyleScheme(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &StyleScheme{}
	cls.Ptr = cret
	return cls
}

// Sets the scheme.
func (x *StyleSchemeChooserButton) SetStyleScheme(SchemeVar *StyleScheme) {
	XGtkSourceStyleSchemeChooserSetStyleScheme(x.GoPointer(), SchemeVar.GoPointer())
}

func init() {
	core.SetPackageName("GTKSOURCE", "gtksourceview-5")
	core.SetSharedLibraries("GTKSOURCE", []string{"libgtksourceview-5.so.0", "libgtksourceview-5.0.dylib"})
}
