// Package adw was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package adw

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Determines when [class@Flap] and [class@Leaflet] will fold.
type FoldThresholdPolicy int

var xFoldThresholdPolicyGLibType func() types.GType

func FoldThresholdPolicyGLibType() types.GType {
	core.LazyRegister(&xFoldThresholdPolicyGLibType, "ADW", "adw_fold_threshold_policy_get_type", false)
	return xFoldThresholdPolicyGLibType()
}

const (

	// Folding is based on the minimum size
	FoldThresholdPolicyMinimumValue FoldThresholdPolicy = 0
	// Folding is based on the natural size
	FoldThresholdPolicyNaturalValue FoldThresholdPolicy = 1
)

func init() {
	core.SetPackageName("ADW", "libadwaita-1")
	core.SetSharedLibraries("ADW", []string{"libadwaita-1.so.0", "libadwaita-1.0.dylib"})
}
