// Package adw was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package adw

import "github.com/bnema/puregotk/pkg/core"

const (
	// Adwaita major version component (e.g. 1 if the version is 1.2.3).
	MAJOR_VERSION int = 1
	// Adwaita micro version component (e.g. 3 if the version is 1.2.3).
	MICRO_VERSION int = 0
	// Adwaita minor version component (e.g. 2 if the version is 1.2.3).
	MINOR_VERSION int = 9
	// Adwaita version, encoded as a string, useful for printing and
	// concatenation.
	VERSION_S string = "1.9.0"
)

var xGetMajorVersion func() uint

// Returns the major version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 1.
//
// This function is in the library, so it represents the libadwaita library your
// code is running against. Contrast with the [const@MAJOR_VERSION] constant,
// which represents the major version of the libadwaita headers you have
// included when compiling your code.
func GetMajorVersion() uint {
	core.LazyRegister(&xGetMajorVersion, "ADW", "adw_get_major_version", false)

	cret := xGetMajorVersion()
	return cret
}

var xGetMicroVersion func() uint

// Returns the micro version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 3.
//
// This function is in the library, so it represents the libadwaita library your
// code is running against. Contrast with the [const@MAJOR_VERSION] constant,
// which represents the micro version of the libadwaita headers you have
// included when compiling your code.
func GetMicroVersion() uint {
	core.LazyRegister(&xGetMicroVersion, "ADW", "adw_get_micro_version", false)

	cret := xGetMicroVersion()
	return cret
}

var xGetMinorVersion func() uint

// Returns the minor version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 2.
//
// This function is in the library, so it represents the libadwaita library your
// code is running against. Contrast with the [const@MAJOR_VERSION] constant,
// which represents the minor version of the libadwaita headers you have
// included when compiling your code.
func GetMinorVersion() uint {
	core.LazyRegister(&xGetMinorVersion, "ADW", "adw_get_minor_version", false)

	cret := xGetMinorVersion()
	return cret
}

func init() {
	core.SetPackageName("ADW", "libadwaita-1")
	core.SetSharedLibraries("ADW", []string{"libadwaita-1.so.0", "libadwaita-1.0.dylib"})
}
