// Package gobject was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gobject

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
)

var xSourceSetClosure func(*glib.Source, *Closure)

// Set the callback for a source as a #GClosure.
//
// If the source is not one of the standard GLib types, the @closure_callback
// and @closure_marshal fields of the #GSourceFuncs structure must have been
// filled in with pointers to appropriate functions.
func SourceSetClosure(SourceVar *glib.Source, ClosureVar *Closure) {
	core.LazyRegister(&xSourceSetClosure, "GOBJECT", "g_source_set_closure", false)

	xSourceSetClosure(SourceVar, ClosureVar)
}

var xSourceSetDummyCallback func(*glib.Source)

// Sets a dummy callback for @source. The callback will do nothing, and
// if the source expects a #gboolean return value, it will return %TRUE.
// (If the source expects any other type of return value, it will return
// a 0/%NULL value; whatever g_value_init() initializes a #GValue to for
// that type.)
//
// If the source is not one of the standard GLib types, the
// @closure_callback and @closure_marshal fields of the #GSourceFuncs
// structure must have been filled in with pointers to appropriate
// functions.
func SourceSetDummyCallback(SourceVar *glib.Source) {
	core.LazyRegister(&xSourceSetDummyCallback, "GOBJECT", "g_source_set_dummy_callback", false)

	xSourceSetDummyCallback(SourceVar)
}

func init() {
	core.SetPackageName("GOBJECT", "gobject-2.0")
	core.SetSharedLibraries("GOBJECT", []string{"libgobject-2.0.so.0", "libgobject-2.0.0.dylib"})
}
