// Package gobject was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gobject

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A `GValueArray` is a container structure to hold an array of generic values.
//
// The prime purpose of a `GValueArray` is for it to be used as an
// object property that holds an array of values. A `GValueArray` wraps
// an array of `GValue` elements in order for it to be used as a boxed
// type through `G_TYPE_VALUE_ARRAY`.
//
// `GValueArray` is deprecated in favour of `GArray` since GLib 2.32.
// It is possible to create a `GArray` that behaves like a `GValueArray`
// by using the size of `GValue` as the element size, and by setting
// [method@GObject.Value.unset] as the clear function using
// [func@GLib.Array.set_clear_func], for instance, the following code:
//
// ```c
//
//	GValueArray *array = g_value_array_new (10);
//
// ```
//
// can be replaced by:
//
// ```c
//
//	GArray *array = g_array_sized_new (FALSE, TRUE, sizeof (GValue), 10);
//	g_array_set_clear_func (array, (GDestroyNotify) g_value_unset);
//
// ```
type ValueArray struct {
	_ structs.HostLayout

	NValues uint

	Values *Value

	NPrealloced uint
}

var xValueArrayGLibType func() types.GType

func ValueArrayGLibType() types.GType {
	core.LazyRegister(&xValueArrayGLibType, "GOBJECT", "g_value_array_get_type", false)
	return xValueArrayGLibType()
}

func (x *ValueArray) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ValueArrayNewFromInternalPtr(ptr uintptr) *ValueArray {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ValueArray)(rawPtr)
}

var xNewValueArray func(uint) uintptr

// Allocate and initialize a new #GValueArray, optionally preserve space
// for @n_prealloced elements. New arrays always contain 0 elements,
// regardless of the value of @n_prealloced.
func NewValueArray(NPreallocedVar uint) *ValueArray {
	core.LazyRegister(&xNewValueArray, "GOBJECT", "g_value_array_new", false)

	cret := xNewValueArray(NPreallocedVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArrayAppend func(uintptr, *Value) uintptr

// Insert a copy of @value as last element of @value_array. If @value is
// %NULL, an uninitialized value is appended.
func (x *ValueArray) Append(ValueVar *Value) *ValueArray {
	core.LazyRegister(&xValueArrayAppend, "GOBJECT", "g_value_array_append", false)

	cret := xValueArrayAppend(x.GoPointer(), ValueVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArrayCopy func(uintptr) uintptr

// Construct an exact copy of a #GValueArray by duplicating all its
// contents.
func (x *ValueArray) Copy() *ValueArray {
	core.LazyRegister(&xValueArrayCopy, "GOBJECT", "g_value_array_copy", false)

	cret := xValueArrayCopy(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArrayFree func(uintptr)

// Free a #GValueArray including its contents.
func (x *ValueArray) Free() {
	core.LazyRegister(&xValueArrayFree, "GOBJECT", "g_value_array_free", false)

	xValueArrayFree(x.GoPointer())
}

var xValueArrayGetNth func(uintptr, uint) uintptr

// Return a pointer to the value at @index_ contained in @value_array.
func (x *ValueArray) GetNth(IndexVar uint) *Value {
	core.LazyRegister(&xValueArrayGetNth, "GOBJECT", "g_value_array_get_nth", false)

	cret := xValueArrayGetNth(x.GoPointer(), IndexVar)
	if cret == 0 {
		return nil
	}
	return (*Value)(unsafe.Pointer(cret))
}

var xValueArrayInsert func(uintptr, uint, *Value) uintptr

// Insert a copy of @value at specified position into @value_array. If @value
// is %NULL, an uninitialized value is inserted.
func (x *ValueArray) Insert(IndexVar uint, ValueVar *Value) *ValueArray {
	core.LazyRegister(&xValueArrayInsert, "GOBJECT", "g_value_array_insert", false)

	cret := xValueArrayInsert(x.GoPointer(), IndexVar, ValueVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArrayPrepend func(uintptr, *Value) uintptr

// Insert a copy of @value as first element of @value_array. If @value is
// %NULL, an uninitialized value is prepended.
func (x *ValueArray) Prepend(ValueVar *Value) *ValueArray {
	core.LazyRegister(&xValueArrayPrepend, "GOBJECT", "g_value_array_prepend", false)

	cret := xValueArrayPrepend(x.GoPointer(), ValueVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArrayRemove func(uintptr, uint) uintptr

// Remove the value at position @index_ from @value_array.
func (x *ValueArray) Remove(IndexVar uint) *ValueArray {
	core.LazyRegister(&xValueArrayRemove, "GOBJECT", "g_value_array_remove", false)

	cret := xValueArrayRemove(x.GoPointer(), IndexVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArraySort func(uintptr, uintptr) uintptr

// Sort @value_array using @compare_func to compare the elements according to
// the semantics of #GCompareFunc.
//
// The current implementation uses the same sorting algorithm as standard
// C qsort() function.
func (x *ValueArray) Sort(CompareFuncVar *glib.CompareFunc) *ValueArray {
	core.LazyRegister(&xValueArraySort, "GOBJECT", "g_value_array_sort", false)

	cret := xValueArraySort(x.GoPointer(), glib.NewCallback(CompareFuncVar))
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

var xValueArraySortWithData func(uintptr, uintptr, uintptr) uintptr

// Sort @value_array using @compare_func to compare the elements according
// to the semantics of #GCompareDataFunc.
//
// The current implementation uses the same sorting algorithm as standard
// C qsort() function.
func (x *ValueArray) SortWithData(CompareFuncVar *glib.CompareDataFunc, UserDataVar uintptr) *ValueArray {
	core.LazyRegister(&xValueArraySortWithData, "GOBJECT", "g_value_array_sort_with_data", false)

	cret := xValueArraySortWithData(x.GoPointer(), glib.NewCallback(CompareFuncVar), UserDataVar)
	if cret == 0 {
		return nil
	}
	return (*ValueArray)(unsafe.Pointer(cret))
}

func init() {
	core.SetPackageName("GOBJECT", "gobject-2.0")
	core.SetSharedLibraries("GOBJECT", []string{"libgobject-2.0.so.0", "libgobject-2.0.0.dylib"})
}
