// Package glib was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package glib

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
)

// The #GSList struct is used for each element in the singly-linked
// list.
type SList struct {
	_ structs.HostLayout

	Data uintptr

	Next *SList
}

func (x *SList) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func SListNewFromInternalPtr(ptr uintptr) *SList {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*SList)(rawPtr)
}

var xClearSlist func(**SList, uintptr)

// Clears a pointer to a #GSList, freeing it and, optionally, freeing its elements using @destroy.
//
// @slist_ptr must be a valid pointer. If @slist_ptr points to a null #GSList, this does nothing.
func ClearSlist(SlistPtrVar **SList, DestroyVar *DestroyNotify) {
	core.LazyRegister(&xClearSlist, "GLIB", "g_clear_slist", false)

	xClearSlist(SlistPtrVar, NewCallbackNullable(DestroyVar))
}

func init() {
	core.SetPackageName("GLIB", "glib-2.0")
	core.SetSharedLibraries("GLIB", []string{"libgobject-2.0.so.0", "libglib-2.0.so.0", "libgobject-2.0.0.dylib", "libglib-2.0.0.dylib"})
}
