// Package glib was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package glib

import "github.com/bnema/puregotk/pkg/core"

var xBookmarkFileErrorQuark func() Quark

func BookmarkFileErrorQuark() Quark {
	core.LazyRegister(&xBookmarkFileErrorQuark, "GLIB", "g_bookmark_file_error_quark", false)

	cret := xBookmarkFileErrorQuark()
	return cret
}

var xConvertErrorQuark func() Quark

func ConvertErrorQuark() Quark {
	core.LazyRegister(&xConvertErrorQuark, "GLIB", "g_convert_error_quark", false)

	cret := xConvertErrorQuark()
	return cret
}

var xFileErrorQuark func() Quark

func FileErrorQuark() Quark {
	core.LazyRegister(&xFileErrorQuark, "GLIB", "g_file_error_quark", false)

	cret := xFileErrorQuark()
	return cret
}

var xIoChannelErrorQuark func() Quark

func IoChannelErrorQuark() Quark {
	core.LazyRegister(&xIoChannelErrorQuark, "GLIB", "g_io_channel_error_quark", false)

	cret := xIoChannelErrorQuark()
	return cret
}

var xKeyFileErrorQuark func() Quark

func KeyFileErrorQuark() Quark {
	core.LazyRegister(&xKeyFileErrorQuark, "GLIB", "g_key_file_error_quark", false)

	cret := xKeyFileErrorQuark()
	return cret
}

var xMarkupErrorQuark func() Quark

func MarkupErrorQuark() Quark {
	core.LazyRegister(&xMarkupErrorQuark, "GLIB", "g_markup_error_quark", false)

	cret := xMarkupErrorQuark()
	return cret
}

var xNumberParserErrorQuark func() Quark

func NumberParserErrorQuark() Quark {
	core.LazyRegister(&xNumberParserErrorQuark, "GLIB", "g_number_parser_error_quark", false)

	cret := xNumberParserErrorQuark()
	return cret
}

var xOptionErrorQuark func() Quark

func OptionErrorQuark() Quark {
	core.LazyRegister(&xOptionErrorQuark, "GLIB", "g_option_error_quark", false)

	cret := xOptionErrorQuark()
	return cret
}

var xRegexErrorQuark func() Quark

func RegexErrorQuark() Quark {
	core.LazyRegister(&xRegexErrorQuark, "GLIB", "g_regex_error_quark", false)

	cret := xRegexErrorQuark()
	return cret
}

var xShellErrorQuark func() Quark

func ShellErrorQuark() Quark {
	core.LazyRegister(&xShellErrorQuark, "GLIB", "g_shell_error_quark", false)

	cret := xShellErrorQuark()
	return cret
}

var xSpawnErrorQuark func() Quark

func SpawnErrorQuark() Quark {
	core.LazyRegister(&xSpawnErrorQuark, "GLIB", "g_spawn_error_quark", false)

	cret := xSpawnErrorQuark()
	return cret
}

var xSpawnExitErrorQuark func() Quark

func SpawnExitErrorQuark() Quark {
	core.LazyRegister(&xSpawnExitErrorQuark, "GLIB", "g_spawn_exit_error_quark", false)

	cret := xSpawnExitErrorQuark()
	return cret
}

var xThreadErrorQuark func() Quark

func ThreadErrorQuark() Quark {
	core.LazyRegister(&xThreadErrorQuark, "GLIB", "g_thread_error_quark", false)

	cret := xThreadErrorQuark()
	return cret
}

var xUriErrorQuark func() Quark

func UriErrorQuark() Quark {
	core.LazyRegister(&xUriErrorQuark, "GLIB", "g_uri_error_quark", false)

	cret := xUriErrorQuark()
	return cret
}

var xVariantParseErrorQuark func() Quark

func VariantParseErrorQuark() Quark {
	core.LazyRegister(&xVariantParseErrorQuark, "GLIB", "g_variant_parse_error_quark", false)

	cret := xVariantParseErrorQuark()
	return cret
}

func init() {
	core.SetPackageName("GLIB", "glib-2.0")
	core.SetSharedLibraries("GLIB", []string{"libgobject-2.0.so.0", "libglib-2.0.so.0", "libgobject-2.0.0.dylib", "libglib-2.0.0.dylib"})
}
