// Package gio was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gio

import (
	"structs"
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// Information about an annotation.
type DBusAnnotationInfo struct {
	_ structs.HostLayout

	RefCount int32

	Key uintptr

	Value uintptr

	Annotations uintptr
}

var xDBusAnnotationInfoGLibType func() types.GType

func DBusAnnotationInfoGLibType() types.GType {
	return xDBusAnnotationInfoGLibType()
}

func (x *DBusAnnotationInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusAnnotationInfoNewFromInternalPtr(ptr uintptr) *DBusAnnotationInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusAnnotationInfo)(rawPtr)
}

var xDBusAnnotationInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusAnnotationInfo) Ref() *DBusAnnotationInfo {
	cret := xDBusAnnotationInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusAnnotationInfo)(unsafe.Pointer(cret))
}

var xDBusAnnotationInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusAnnotationInfo) Unref() {
	xDBusAnnotationInfoUnref(x.GoPointer())
}

// Information about an argument for a method or a signal.
type DBusArgInfo struct {
	_ structs.HostLayout

	RefCount int32

	Name uintptr

	Signature uintptr

	Annotations uintptr
}

var xDBusArgInfoGLibType func() types.GType

func DBusArgInfoGLibType() types.GType {
	return xDBusArgInfoGLibType()
}

func (x *DBusArgInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusArgInfoNewFromInternalPtr(ptr uintptr) *DBusArgInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusArgInfo)(rawPtr)
}

var xDBusArgInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusArgInfo) Ref() *DBusArgInfo {
	cret := xDBusArgInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusArgInfo)(unsafe.Pointer(cret))
}

var xDBusArgInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusArgInfo) Unref() {
	xDBusArgInfoUnref(x.GoPointer())
}

// Information about a D-Bus interface.
type DBusInterfaceInfo struct {
	_ structs.HostLayout

	RefCount int32

	Name uintptr

	Methods uintptr

	Signals uintptr

	Properties uintptr

	Annotations uintptr
}

var xDBusInterfaceInfoGLibType func() types.GType

func DBusInterfaceInfoGLibType() types.GType {
	return xDBusInterfaceInfoGLibType()
}

func (x *DBusInterfaceInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusInterfaceInfoNewFromInternalPtr(ptr uintptr) *DBusInterfaceInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusInterfaceInfo)(rawPtr)
}

var xDBusInterfaceInfoCacheBuild func(uintptr)

// Builds a lookup-cache to speed up
// g_dbus_interface_info_lookup_method(),
// g_dbus_interface_info_lookup_signal() and
// g_dbus_interface_info_lookup_property().
//
// If this has already been called with @info, the existing cache is
// used and its use count is increased.
//
// Note that @info cannot be modified until
// g_dbus_interface_info_cache_release() is called.
func (x *DBusInterfaceInfo) CacheBuild() {
	xDBusInterfaceInfoCacheBuild(x.GoPointer())
}

var xDBusInterfaceInfoCacheRelease func(uintptr)

// Decrements the usage count for the cache for @info built by
// g_dbus_interface_info_cache_build() (if any) and frees the
// resources used by the cache if the usage count drops to zero.
func (x *DBusInterfaceInfo) CacheRelease() {
	xDBusInterfaceInfoCacheRelease(x.GoPointer())
}

var xDBusInterfaceInfoGenerateXml func(uintptr, uint, *glib.String)

// Appends an XML representation of @info (and its children) to @string_builder.
//
// This function is typically used for generating introspection XML
// documents at run-time for handling the
// `org.freedesktop.DBus.Introspectable.Introspect`
// method.
func (x *DBusInterfaceInfo) GenerateXml(IndentVar uint, StringBuilderVar *glib.String) {
	xDBusInterfaceInfoGenerateXml(x.GoPointer(), IndentVar, StringBuilderVar)
}

var xDBusInterfaceInfoLookupMethod func(uintptr, string) uintptr

// Looks up information about a method.
//
// The cost of this function is O(n) in number of methods unless
// g_dbus_interface_info_cache_build() has been used on @info.
func (x *DBusInterfaceInfo) LookupMethod(NameVar string) *DBusMethodInfo {
	cret := xDBusInterfaceInfoLookupMethod(x.GoPointer(), NameVar)
	if cret == 0 {
		return nil
	}
	return (*DBusMethodInfo)(unsafe.Pointer(cret))
}

var xDBusInterfaceInfoLookupProperty func(uintptr, string) uintptr

// Looks up information about a property.
//
// The cost of this function is O(n) in number of properties unless
// g_dbus_interface_info_cache_build() has been used on @info.
func (x *DBusInterfaceInfo) LookupProperty(NameVar string) *DBusPropertyInfo {
	cret := xDBusInterfaceInfoLookupProperty(x.GoPointer(), NameVar)
	if cret == 0 {
		return nil
	}
	return (*DBusPropertyInfo)(unsafe.Pointer(cret))
}

var xDBusInterfaceInfoLookupSignal func(uintptr, string) uintptr

// Looks up information about a signal.
//
// The cost of this function is O(n) in number of signals unless
// g_dbus_interface_info_cache_build() has been used on @info.
func (x *DBusInterfaceInfo) LookupSignal(NameVar string) *DBusSignalInfo {
	cret := xDBusInterfaceInfoLookupSignal(x.GoPointer(), NameVar)
	if cret == 0 {
		return nil
	}
	return (*DBusSignalInfo)(unsafe.Pointer(cret))
}

var xDBusInterfaceInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusInterfaceInfo) Ref() *DBusInterfaceInfo {
	cret := xDBusInterfaceInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusInterfaceInfo)(unsafe.Pointer(cret))
}

var xDBusInterfaceInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusInterfaceInfo) Unref() {
	xDBusInterfaceInfoUnref(x.GoPointer())
}

// Information about a method on a D-Bus interface.
type DBusMethodInfo struct {
	_ structs.HostLayout

	RefCount int32

	Name uintptr

	InArgs uintptr

	OutArgs uintptr

	Annotations uintptr
}

var xDBusMethodInfoGLibType func() types.GType

func DBusMethodInfoGLibType() types.GType {
	return xDBusMethodInfoGLibType()
}

func (x *DBusMethodInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusMethodInfoNewFromInternalPtr(ptr uintptr) *DBusMethodInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusMethodInfo)(rawPtr)
}

var xDBusMethodInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusMethodInfo) Ref() *DBusMethodInfo {
	cret := xDBusMethodInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusMethodInfo)(unsafe.Pointer(cret))
}

var xDBusMethodInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusMethodInfo) Unref() {
	xDBusMethodInfoUnref(x.GoPointer())
}

// Information about nodes in a remote object hierarchy.
type DBusNodeInfo struct {
	_ structs.HostLayout

	RefCount int32

	Path uintptr

	Interfaces uintptr

	Nodes uintptr

	Annotations uintptr
}

var xDBusNodeInfoGLibType func() types.GType

func DBusNodeInfoGLibType() types.GType {
	return xDBusNodeInfoGLibType()
}

func (x *DBusNodeInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusNodeInfoNewFromInternalPtr(ptr uintptr) *DBusNodeInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusNodeInfo)(rawPtr)
}

var xNewDBusNodeInfoForXml func(string, **glib.Error) uintptr

// Parses @xml_data and returns a #GDBusNodeInfo representing the data.
//
// The introspection XML must contain exactly one top-level
// `&lt;node&gt;` element.
//
// Note that this routine is using a
// [GMarkup](../glib/markup.html)-based
// parser that only accepts a subset of valid XML documents.
func NewDBusNodeInfoForXml(XmlDataVar string) (*DBusNodeInfo, error) {
	var cerr *glib.Error

	cret := xNewDBusNodeInfoForXml(XmlDataVar, &cerr)
	if cerr != nil {
		return nil, cerr
	}
	if cret == 0 {
		return nil, nil
	}
	return (*DBusNodeInfo)(unsafe.Pointer(cret)), nil
}

var xDBusNodeInfoGenerateXml func(uintptr, uint, *glib.String)

// Appends an XML representation of @info (and its children) to @string_builder.
//
// This function is typically used for generating introspection XML documents at run-time for
// handling the `org.freedesktop.DBus.Introspectable.Introspect`  method.
func (x *DBusNodeInfo) GenerateXml(IndentVar uint, StringBuilderVar *glib.String) {
	xDBusNodeInfoGenerateXml(x.GoPointer(), IndentVar, StringBuilderVar)
}

var xDBusNodeInfoLookupInterface func(uintptr, string) uintptr

// Looks up information about an interface.
//
// The cost of this function is O(n) in number of interfaces.
func (x *DBusNodeInfo) LookupInterface(NameVar string) *DBusInterfaceInfo {
	cret := xDBusNodeInfoLookupInterface(x.GoPointer(), NameVar)
	if cret == 0 {
		return nil
	}
	return (*DBusInterfaceInfo)(unsafe.Pointer(cret))
}

var xDBusNodeInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusNodeInfo) Ref() *DBusNodeInfo {
	cret := xDBusNodeInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusNodeInfo)(unsafe.Pointer(cret))
}

var xDBusNodeInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusNodeInfo) Unref() {
	xDBusNodeInfoUnref(x.GoPointer())
}

// Information about a D-Bus property on a D-Bus interface.
type DBusPropertyInfo struct {
	_ structs.HostLayout

	RefCount int32

	Name uintptr

	Signature uintptr

	Flags DBusPropertyInfoFlags

	Annotations uintptr
}

var xDBusPropertyInfoGLibType func() types.GType

func DBusPropertyInfoGLibType() types.GType {
	return xDBusPropertyInfoGLibType()
}

func (x *DBusPropertyInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusPropertyInfoNewFromInternalPtr(ptr uintptr) *DBusPropertyInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusPropertyInfo)(rawPtr)
}

var xDBusPropertyInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusPropertyInfo) Ref() *DBusPropertyInfo {
	cret := xDBusPropertyInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusPropertyInfo)(unsafe.Pointer(cret))
}

var xDBusPropertyInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusPropertyInfo) Unref() {
	xDBusPropertyInfoUnref(x.GoPointer())
}

// Information about a signal on a D-Bus interface.
type DBusSignalInfo struct {
	_ structs.HostLayout

	RefCount int32

	Name uintptr

	Args uintptr

	Annotations uintptr
}

var xDBusSignalInfoGLibType func() types.GType

func DBusSignalInfoGLibType() types.GType {
	return xDBusSignalInfoGLibType()
}

func (x *DBusSignalInfo) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func DBusSignalInfoNewFromInternalPtr(ptr uintptr) *DBusSignalInfo {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*DBusSignalInfo)(rawPtr)
}

var xDBusSignalInfoRef func(uintptr) uintptr

// If @info is statically allocated does nothing. Otherwise increases
// the reference count.
func (x *DBusSignalInfo) Ref() *DBusSignalInfo {
	cret := xDBusSignalInfoRef(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*DBusSignalInfo)(unsafe.Pointer(cret))
}

var xDBusSignalInfoUnref func(uintptr)

// If @info is statically allocated, does nothing. Otherwise decreases
// the reference count of @info. When its reference count drops to 0,
// the memory used is freed.
func (x *DBusSignalInfo) Unref() {
	xDBusSignalInfoUnref(x.GoPointer())
}

var xDbusAnnotationInfoLookup func(uintptr, string) string

// Looks up the value of an annotation.
//
// The cost of this function is O(n) in number of annotations.
func DbusAnnotationInfoLookup(AnnotationsVar uintptr, NameVar string) string {
	cret := xDbusAnnotationInfoLookup(AnnotationsVar, NameVar)
	return cret
}

func init() {
	core.SetPackageName("GIO", "gio-2.0")
	core.SetSharedLibraries("GIO", []string{"libgio-2.0.so.0", "libgio-2.0.0.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GIO") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xDbusAnnotationInfoLookup, libs, "g_dbus_annotation_info_lookup")

	core.PuregoSafeRegister(&xDBusAnnotationInfoGLibType, libs, "g_dbus_annotation_info_get_type")

	core.PuregoSafeRegister(&xDBusAnnotationInfoRef, libs, "g_dbus_annotation_info_ref")
	core.PuregoSafeRegister(&xDBusAnnotationInfoUnref, libs, "g_dbus_annotation_info_unref")

	core.PuregoSafeRegister(&xDBusArgInfoGLibType, libs, "g_dbus_arg_info_get_type")

	core.PuregoSafeRegister(&xDBusArgInfoRef, libs, "g_dbus_arg_info_ref")
	core.PuregoSafeRegister(&xDBusArgInfoUnref, libs, "g_dbus_arg_info_unref")

	core.PuregoSafeRegister(&xDBusInterfaceInfoGLibType, libs, "g_dbus_interface_info_get_type")

	core.PuregoSafeRegister(&xDBusInterfaceInfoCacheBuild, libs, "g_dbus_interface_info_cache_build")
	core.PuregoSafeRegister(&xDBusInterfaceInfoCacheRelease, libs, "g_dbus_interface_info_cache_release")
	core.PuregoSafeRegister(&xDBusInterfaceInfoGenerateXml, libs, "g_dbus_interface_info_generate_xml")
	core.PuregoSafeRegister(&xDBusInterfaceInfoLookupMethod, libs, "g_dbus_interface_info_lookup_method")
	core.PuregoSafeRegister(&xDBusInterfaceInfoLookupProperty, libs, "g_dbus_interface_info_lookup_property")
	core.PuregoSafeRegister(&xDBusInterfaceInfoLookupSignal, libs, "g_dbus_interface_info_lookup_signal")
	core.PuregoSafeRegister(&xDBusInterfaceInfoRef, libs, "g_dbus_interface_info_ref")
	core.PuregoSafeRegister(&xDBusInterfaceInfoUnref, libs, "g_dbus_interface_info_unref")

	core.PuregoSafeRegister(&xDBusMethodInfoGLibType, libs, "g_dbus_method_info_get_type")

	core.PuregoSafeRegister(&xDBusMethodInfoRef, libs, "g_dbus_method_info_ref")
	core.PuregoSafeRegister(&xDBusMethodInfoUnref, libs, "g_dbus_method_info_unref")

	core.PuregoSafeRegister(&xDBusNodeInfoGLibType, libs, "g_dbus_node_info_get_type")

	core.PuregoSafeRegister(&xNewDBusNodeInfoForXml, libs, "g_dbus_node_info_new_for_xml")

	core.PuregoSafeRegister(&xDBusNodeInfoGenerateXml, libs, "g_dbus_node_info_generate_xml")
	core.PuregoSafeRegister(&xDBusNodeInfoLookupInterface, libs, "g_dbus_node_info_lookup_interface")
	core.PuregoSafeRegister(&xDBusNodeInfoRef, libs, "g_dbus_node_info_ref")
	core.PuregoSafeRegister(&xDBusNodeInfoUnref, libs, "g_dbus_node_info_unref")

	core.PuregoSafeRegister(&xDBusPropertyInfoGLibType, libs, "g_dbus_property_info_get_type")

	core.PuregoSafeRegister(&xDBusPropertyInfoRef, libs, "g_dbus_property_info_ref")
	core.PuregoSafeRegister(&xDBusPropertyInfoUnref, libs, "g_dbus_property_info_unref")

	core.PuregoSafeRegister(&xDBusSignalInfoGLibType, libs, "g_dbus_signal_info_get_type")

	core.PuregoSafeRegister(&xDBusSignalInfoRef, libs, "g_dbus_signal_info_ref")
	core.PuregoSafeRegister(&xDBusSignalInfoUnref, libs, "g_dbus_signal_info_unref")
}
