// Package gio was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gio

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type IPv6TclassMessageClass struct {
	_ structs.HostLayout

	ParentClass SocketControlMessageClass
}

func (x *IPv6TclassMessageClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func IPv6TclassMessageClassNewFromInternalPtr(ptr uintptr) *IPv6TclassMessageClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*IPv6TclassMessageClass)(rawPtr)
}

// Contains the Traffic Class byte of an IPv6 header.
//
// This consists of the DSCP field as per
// [RFC 2474](https://www.rfc-editor.org/rfc/rfc2474#section-3),
// and the ECN field as per
// [RFC 3168](https://www.rfc-editor.org/rfc/rfc3168#section-5).
//
// It may be received using [method@Gio.Socket.receive_message] over UDP sockets
// (i.e. sockets in the `G_SOCKET_FAMILY_IPV6` family with
// `G_SOCKET_TYPE_DATAGRAM` type). The message is not meant for sending. To set
// Traffic Class field to be used in datagrams sent on a [class@Gio.Socket] use:
// ```c
// g_socket_set_option (socket, IPPROTO_IPV6, IPV6_TCLASS, &lt;TC value&gt;, &amp;error);
// ```
type IPv6TclassMessage struct {
	SocketControlMessage
}

var xIPv6TclassMessageGLibType func() types.GType

func IPv6TclassMessageGLibType() types.GType {
	core.LazyRegister(&xIPv6TclassMessageGLibType, "GIO", "g_ipv6_tclass_message_get_type", false)
	return xIPv6TclassMessageGLibType()
}

func IPv6TclassMessageNewFromInternalPtr(ptr uintptr) *IPv6TclassMessage {
	cls := &IPv6TclassMessage{}
	cls.Ptr = ptr
	return cls
}

var xNewIPv6TclassMessage func(byte, EcnCodePoint) uintptr

// Creates a new traffic class message with given DSCP and ECN values.
func NewIPv6TclassMessage(DscpVar byte, EcnVar EcnCodePoint) *IPv6TclassMessage {
	core.LazyRegister(&xNewIPv6TclassMessage, "GIO", "g_ipv6_tclass_message_new", false)
	var cls *IPv6TclassMessage

	cret := xNewIPv6TclassMessage(DscpVar, EcnVar)

	if cret == 0 {
		return nil
	}
	cls = &IPv6TclassMessage{}
	cls.Ptr = cret
	return cls
}

var xIPv6TclassMessageGetDscp func(uintptr) byte

// Gets the differentiated services code point stored in @message.
func (x *IPv6TclassMessage) GetDscp() byte {
	core.LazyRegister(&xIPv6TclassMessageGetDscp, "GIO", "g_ipv6_tclass_message_get_dscp", false)

	cret := xIPv6TclassMessageGetDscp(x.GoPointer())
	return cret
}

var xIPv6TclassMessageGetEcn func(uintptr) EcnCodePoint

// Gets the Explicit Congestion Notification code point stored in @message.
func (x *IPv6TclassMessage) GetEcn() EcnCodePoint {
	core.LazyRegister(&xIPv6TclassMessageGetEcn, "GIO", "g_ipv6_tclass_message_get_ecn", false)

	cret := xIPv6TclassMessageGetEcn(x.GoPointer())
	return cret
}

func (c *IPv6TclassMessage) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *IPv6TclassMessage) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GIO", "gio-2.0")
	core.SetSharedLibraries("GIO", []string{"libgio-2.0.so.0", "libgio-2.0.0.dylib"})
}
