// Package gio was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gio

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type ThreadedResolverClass struct {
	_ structs.HostLayout

	ParentClass ResolverClass
}

func (x *ThreadedResolverClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func ThreadedResolverClassNewFromInternalPtr(ptr uintptr) *ThreadedResolverClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*ThreadedResolverClass)(rawPtr)
}

// #GThreadedResolver is an implementation of #GResolver which calls the libc
// lookup functions in threads to allow them to run asynchronously.
type ThreadedResolver struct {
	Resolver
}

var xThreadedResolverGLibType func() types.GType

func ThreadedResolverGLibType() types.GType {
	core.LazyRegister(&xThreadedResolverGLibType, "GIO", "g_threaded_resolver_get_type", false)
	return xThreadedResolverGLibType()
}

func ThreadedResolverNewFromInternalPtr(ptr uintptr) *ThreadedResolver {
	cls := &ThreadedResolver{}
	cls.Ptr = ptr
	return cls
}

func (c *ThreadedResolver) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ThreadedResolver) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GIO", "gio-2.0")
	core.SetSharedLibraries("GIO", []string{"libgio-2.0.so.0", "libgio-2.0.0.dylib"})
}
