// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"structs"
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject/types"
)

type BroadwayRendererClass struct {
	_ structs.HostLayout
}

func (x *BroadwayRendererClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

func BroadwayRendererClassNewFromInternalPtr(ptr uintptr) *BroadwayRendererClass {
	if ptr == 0 {
		return nil
	}
	rawPtr := *(*unsafe.Pointer)(unsafe.Pointer(&ptr))
	return (*BroadwayRendererClass)(rawPtr)
}

// A Broadway based renderer.
//
// See [class@Gsk.Renderer].
type BroadwayRenderer struct {
	Renderer
}

var xBroadwayRendererGLibType func() types.GType

func BroadwayRendererGLibType() types.GType {
	core.LazyRegister(&xBroadwayRendererGLibType, "GSK", "gsk_broadway_renderer_get_type", false)
	return xBroadwayRendererGLibType()
}

func BroadwayRendererNewFromInternalPtr(ptr uintptr) *BroadwayRenderer {
	cls := &BroadwayRenderer{}
	cls.Ptr = ptr
	return cls
}

var xNewBroadwayRenderer func() uintptr

// Creates a new Broadway renderer.
//
// The Broadway renderer is the default renderer for the broadway backend.
// It will only work with broadway surfaces, otherwise it will fail the
// call to gsk_renderer_realize().
//
// This function is only available when GTK was compiled with Broadway
// support.
func NewBroadwayRenderer() *BroadwayRenderer {
	core.LazyRegister(&xNewBroadwayRenderer, "GSK", "gsk_broadway_renderer_new", false)
	var cls *BroadwayRenderer

	cret := xNewBroadwayRenderer()

	if cret == 0 {
		return nil
	}
	cls = &BroadwayRenderer{}
	cls.Ptr = cret
	return cls
}

func (c *BroadwayRenderer) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *BroadwayRenderer) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
