// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/cairo"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/graphene"
)

// A render node for a Cairo surface.
type CairoNode struct {
	RenderNode
}

var xCairoNodeGLibType func() types.GType

func CairoNodeGLibType() types.GType {
	core.LazyRegister(&xCairoNodeGLibType, "GSK", "gsk_cairo_node_get_type", false)
	return xCairoNodeGLibType()
}

func CairoNodeNewFromInternalPtr(ptr uintptr) *CairoNode {
	cls := &CairoNode{}
	cls.Ptr = ptr
	return cls
}

var xNewCairoNode func(*graphene.Rect) uintptr

// Creates a `GskRenderNode` that will render a cairo surface
// into the area given by @bounds.
//
// You can draw to the cairo surface using [method@Gsk.CairoNode.get_draw_context].
func NewCairoNode(BoundsVar *graphene.Rect) *CairoNode {
	core.LazyRegister(&xNewCairoNode, "GSK", "gsk_cairo_node_new", false)
	var cls *CairoNode

	cret := xNewCairoNode(BoundsVar)

	if cret == 0 {
		return nil
	}
	cls = &CairoNode{}
	cls.Ptr = cret
	return cls
}

var xCairoNodeGetDrawContext func(uintptr) uintptr

// Creates a Cairo context for drawing using the surface associated
// to the render node.
//
// If no surface exists yet, a surface will be created optimized for
// rendering to @renderer.
func (x *CairoNode) GetDrawContext() *cairo.Context {
	core.LazyRegister(&xCairoNodeGetDrawContext, "GSK", "gsk_cairo_node_get_draw_context", false)

	cret := xCairoNodeGetDrawContext(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*cairo.Context)(unsafe.Pointer(cret))
}

var xCairoNodeGetSurface func(uintptr) uintptr

// Retrieves the Cairo surface used by the render node.
func (x *CairoNode) GetSurface() *cairo.Surface {
	core.LazyRegister(&xCairoNodeGetSurface, "GSK", "gsk_cairo_node_get_surface", false)

	cret := xCairoNodeGetSurface(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*cairo.Surface)(unsafe.Pointer(cret))
}

func (c *CairoNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *CairoNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
