// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import "github.com/bnema/puregotk/pkg/core"

var xComponentTransferEqual func(uintptr, uintptr) bool

// Compares two component transfers for equality.
func ComponentTransferEqual(SelfVar uintptr, OtherVar uintptr) bool {
	core.LazyRegister(&xComponentTransferEqual, "GSK", "gsk_component_transfer_equal", false)

	cret := xComponentTransferEqual(SelfVar, OtherVar)
	return cret
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
