// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node cross fading between two child nodes.
type CrossFadeNode struct {
	RenderNode
}

var xCrossFadeNodeGLibType func() types.GType

func CrossFadeNodeGLibType() types.GType {
	core.LazyRegister(&xCrossFadeNodeGLibType, "GSK", "gsk_cross_fade_node_get_type", false)
	return xCrossFadeNodeGLibType()
}

func CrossFadeNodeNewFromInternalPtr(ptr uintptr) *CrossFadeNode {
	cls := &CrossFadeNode{}
	cls.Ptr = ptr
	return cls
}

var xNewCrossFadeNode func(uintptr, uintptr, float32) uintptr

// Creates a `GskRenderNode` that will do a cross-fade between @start and @end.
func NewCrossFadeNode(StartVar *RenderNode, EndVar *RenderNode, ProgressVar float32) *CrossFadeNode {
	core.LazyRegister(&xNewCrossFadeNode, "GSK", "gsk_cross_fade_node_new", false)
	var cls *CrossFadeNode

	cret := xNewCrossFadeNode(StartVar.GoPointer(), EndVar.GoPointer(), ProgressVar)

	if cret == 0 {
		return nil
	}
	cls = &CrossFadeNode{}
	cls.Ptr = cret
	return cls
}

var xCrossFadeNodeGetEndChild func(uintptr) uintptr

// Retrieves the child `GskRenderNode` at the end of the cross-fade.
func (x *CrossFadeNode) GetEndChild() *RenderNode {
	core.LazyRegister(&xCrossFadeNodeGetEndChild, "GSK", "gsk_cross_fade_node_get_end_child", false)
	var cls *RenderNode

	cret := xCrossFadeNodeGetEndChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xCrossFadeNodeGetProgress func(uintptr) float32

// Retrieves the progress value of the cross fade.
func (x *CrossFadeNode) GetProgress() float32 {
	core.LazyRegister(&xCrossFadeNodeGetProgress, "GSK", "gsk_cross_fade_node_get_progress", false)

	cret := xCrossFadeNodeGetProgress(x.GoPointer())
	return cret
}

var xCrossFadeNodeGetStartChild func(uintptr) uintptr

// Retrieves the child `GskRenderNode` at the beginning of the cross-fade.
func (x *CrossFadeNode) GetStartChild() *RenderNode {
	core.LazyRegister(&xCrossFadeNodeGetStartChild, "GSK", "gsk_cross_fade_node_get_start_child", false)
	var cls *RenderNode

	cret := xCrossFadeNodeGetStartChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

func (c *CrossFadeNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *CrossFadeNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
