// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/graphene"
)

// A render node applying a rectangular clip to its single child node.
type ClipNode struct {
	RenderNode
}

var xClipNodeGLibType func() types.GType

func ClipNodeGLibType() types.GType {
	return xClipNodeGLibType()
}

func ClipNodeNewFromInternalPtr(ptr uintptr) *ClipNode {
	cls := &ClipNode{}
	cls.Ptr = ptr
	return cls
}

var xNewClipNode func(uintptr, *graphene.Rect) uintptr

// Creates a `GskRenderNode` that will clip the @child to the area
// given by @clip.
func NewClipNode(ChildVar *RenderNode, ClipVar *graphene.Rect) *ClipNode {
	var cls *ClipNode

	cret := xNewClipNode(ChildVar.GoPointer(), ClipVar)

	if cret == 0 {
		return nil
	}
	cls = &ClipNode{}
	cls.Ptr = cret
	return cls
}

var xClipNodeGetChild func(uintptr) uintptr

// Gets the child node that is getting clipped by the given @node.
func (x *ClipNode) GetChild() *RenderNode {
	var cls *RenderNode

	cret := xClipNodeGetChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xClipNodeGetClip func(uintptr) uintptr

// Retrieves the clip rectangle for @node.
func (x *ClipNode) GetClip() *graphene.Rect {
	cret := xClipNodeGetClip(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*graphene.Rect)(unsafe.Pointer(cret))
}

func (c *ClipNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ClipNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xClipNodeGLibType, libs, "gsk_clip_node_get_type")

	core.PuregoSafeRegister(&xNewClipNode, libs, "gsk_clip_node_new")

	core.PuregoSafeRegister(&xClipNodeGetChild, libs, "gsk_clip_node_get_child")
	core.PuregoSafeRegister(&xClipNodeGetClip, libs, "gsk_clip_node_get_clip")
}
