// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node that emits a debugging message when drawing its
// child node.
type DebugNode struct {
	RenderNode
}

var xDebugNodeGLibType func() types.GType

func DebugNodeGLibType() types.GType {
	return xDebugNodeGLibType()
}

func DebugNodeNewFromInternalPtr(ptr uintptr) *DebugNode {
	cls := &DebugNode{}
	cls.Ptr = ptr
	return cls
}

var xNewDebugNode func(uintptr, string) uintptr

// Creates a `GskRenderNode` that will add debug information about
// the given @child.
//
// Adding this node has no visual effect.
func NewDebugNode(ChildVar *RenderNode, MessageVar string) *DebugNode {
	var cls *DebugNode

	cret := xNewDebugNode(ChildVar.GoPointer(), MessageVar)

	if cret == 0 {
		return nil
	}
	cls = &DebugNode{}
	cls.Ptr = cret
	return cls
}

var xDebugNodeGetChild func(uintptr) uintptr

// Gets the child node that is getting drawn by the given @node.
func (x *DebugNode) GetChild() *RenderNode {
	var cls *RenderNode

	cret := xDebugNodeGetChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xDebugNodeGetMessage func(uintptr) string

// Gets the debug message that was set on this node
func (x *DebugNode) GetMessage() string {
	cret := xDebugNodeGetMessage(x.GoPointer())
	return cret
}

func (c *DebugNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *DebugNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xDebugNodeGLibType, libs, "gsk_debug_node_get_type")

	core.PuregoSafeRegister(&xNewDebugNode, libs, "gsk_debug_node_new")

	core.PuregoSafeRegister(&xDebugNodeGetChild, libs, "gsk_debug_node_get_child")
	core.PuregoSafeRegister(&xDebugNodeGetMessage, libs, "gsk_debug_node_get_message")
}
