// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node filling the area given by [struct@Gsk.Path]
// and [enum@Gsk.FillRule] with the child node.
type FillNode struct {
	RenderNode
}

var xFillNodeGLibType func() types.GType

func FillNodeGLibType() types.GType {
	return xFillNodeGLibType()
}

func FillNodeNewFromInternalPtr(ptr uintptr) *FillNode {
	cls := &FillNode{}
	cls.Ptr = ptr
	return cls
}

var xNewFillNode func(uintptr, *Path, FillRule) uintptr

// Creates a `GskRenderNode` that will fill the @child in the area
// given by @path and @fill_rule.
func NewFillNode(ChildVar *RenderNode, PathVar *Path, FillRuleVar FillRule) *FillNode {
	var cls *FillNode

	cret := xNewFillNode(ChildVar.GoPointer(), PathVar, FillRuleVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &FillNode{}
	cls.Ptr = cret
	return cls
}

var xFillNodeGetChild func(uintptr) uintptr

// Gets the child node that is getting drawn by the given @node.
func (x *FillNode) GetChild() *RenderNode {
	var cls *RenderNode

	cret := xFillNodeGetChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xFillNodeGetFillRule func(uintptr) FillRule

// Retrieves the fill rule used to determine how the path is filled.
func (x *FillNode) GetFillRule() FillRule {
	cret := xFillNodeGetFillRule(x.GoPointer())
	return cret
}

var xFillNodeGetPath func(uintptr) uintptr

// Retrieves the path used to describe the area filled with the contents of
// the @node.
func (x *FillNode) GetPath() *Path {
	cret := xFillNodeGetPath(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Path)(unsafe.Pointer(cret))
}

func (c *FillNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *FillNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xFillNodeGLibType, libs, "gsk_fill_node_get_type")

	core.PuregoSafeRegister(&xNewFillNode, libs, "gsk_fill_node_new")

	core.PuregoSafeRegister(&xFillNodeGetChild, libs, "gsk_fill_node_get_child")
	core.PuregoSafeRegister(&xFillNodeGetFillRule, libs, "gsk_fill_node_get_fill_rule")
	core.PuregoSafeRegister(&xFillNodeGetPath, libs, "gsk_fill_node_get_path")
}
