// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/glib"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/graphene"
)

// A render node using a GL shader when drawing its children nodes.
type GLShaderNode struct {
	RenderNode
}

var xGLShaderNodeGLibType func() types.GType

func GLShaderNodeGLibType() types.GType {
	return xGLShaderNodeGLibType()
}

func GLShaderNodeNewFromInternalPtr(ptr uintptr) *GLShaderNode {
	cls := &GLShaderNode{}
	cls.Ptr = ptr
	return cls
}

var xNewGLShaderNode func(uintptr, *graphene.Rect, *glib.Bytes, uintptr, uint) uintptr

// Creates a `GskRenderNode` that will render the given @shader into the
// area given by @bounds.
//
// The @args is a block of data to use for uniform input, as per types and
// offsets defined by the @shader. Normally this is generated by
// [method@Gsk.GLShader.format_args] or [struct@Gsk.ShaderArgsBuilder].
//
// See [class@Gsk.GLShader] for details about how the shader should be written.
//
// All the children will be rendered into textures (if they aren't already
// `GskTextureNodes`, which will be used directly). These textures will be
// sent as input to the shader.
//
// If the renderer doesn't support GL shaders, or if there is any problem
// when compiling the shader, then the node will draw pink. You should use
// [method@Gsk.GLShader.compile] to ensure the @shader will work for the
// renderer before using it.
func NewGLShaderNode(ShaderVar *GLShader, BoundsVar *graphene.Rect, ArgsVar *glib.Bytes, ChildrenVar uintptr, NChildrenVar uint) *GLShaderNode {
	var cls *GLShaderNode

	cret := xNewGLShaderNode(ShaderVar.GoPointer(), BoundsVar, ArgsVar, ChildrenVar, NChildrenVar)

	if cret == 0 {
		return nil
	}
	cls = &GLShaderNode{}
	cls.Ptr = cret
	return cls
}

var xGLShaderNodeGetArgs func(uintptr) uintptr

// Gets args for the node.
func (x *GLShaderNode) GetArgs() *glib.Bytes {
	cret := xGLShaderNodeGetArgs(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*glib.Bytes)(unsafe.Pointer(cret))
}

var xGLShaderNodeGetChild func(uintptr, uint) uintptr

// Gets one of the children.
func (x *GLShaderNode) GetChild(IdxVar uint) *RenderNode {
	var cls *RenderNode

	cret := xGLShaderNodeGetChild(x.GoPointer(), IdxVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xGLShaderNodeGetNChildren func(uintptr) uint

// Returns the number of children
func (x *GLShaderNode) GetNChildren() uint {
	cret := xGLShaderNodeGetNChildren(x.GoPointer())
	return cret
}

var xGLShaderNodeGetShader func(uintptr) uintptr

// Gets shader code for the node.
func (x *GLShaderNode) GetShader() *GLShader {
	var cls *GLShader

	cret := xGLShaderNodeGetShader(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &GLShader{}
	cls.Ptr = cret
	return cls
}

func (c *GLShaderNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *GLShaderNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xGLShaderNodeGLibType, libs, "gsk_gl_shader_node_get_type")

	core.PuregoSafeRegister(&xNewGLShaderNode, libs, "gsk_gl_shader_node_new")

	core.PuregoSafeRegister(&xGLShaderNodeGetArgs, libs, "gsk_gl_shader_node_get_args")
	core.PuregoSafeRegister(&xGLShaderNodeGetChild, libs, "gsk_gl_shader_node_get_child")
	core.PuregoSafeRegister(&xGLShaderNodeGetNChildren, libs, "gsk_gl_shader_node_get_n_children")
	core.PuregoSafeRegister(&xGLShaderNodeGetShader, libs, "gsk_gl_shader_node_get_shader")
}
