// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/purego"
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node for an inset shadow.
type InsetShadowNode struct {
	RenderNode
}

var xInsetShadowNodeGLibType func() types.GType

func InsetShadowNodeGLibType() types.GType {
	return xInsetShadowNodeGLibType()
}

func InsetShadowNodeNewFromInternalPtr(ptr uintptr) *InsetShadowNode {
	cls := &InsetShadowNode{}
	cls.Ptr = ptr
	return cls
}

var xNewInsetShadowNode func(*RoundedRect, *gdk.RGBA, float32, float32, float32, float32) uintptr

// Creates a `GskRenderNode` that will render an inset shadow
// into the box given by @outline.
func NewInsetShadowNode(OutlineVar *RoundedRect, ColorVar *gdk.RGBA, DxVar float32, DyVar float32, SpreadVar float32, BlurRadiusVar float32) *InsetShadowNode {
	var cls *InsetShadowNode

	cret := xNewInsetShadowNode(OutlineVar, ColorVar, DxVar, DyVar, SpreadVar, BlurRadiusVar)

	if cret == 0 {
		return nil
	}
	cls = &InsetShadowNode{}
	cls.Ptr = cret
	return cls
}

var xInsetShadowNodeGetBlurRadius func(uintptr) float32

// Retrieves the blur radius to apply to the shadow.
func (x *InsetShadowNode) GetBlurRadius() float32 {
	cret := xInsetShadowNodeGetBlurRadius(x.GoPointer())
	return cret
}

var xInsetShadowNodeGetColor func(uintptr) uintptr

// Retrieves the color of the inset shadow.
//
// The value returned by this function will not be correct
// if the render node was created for a non-sRGB color.
func (x *InsetShadowNode) GetColor() *gdk.RGBA {
	cret := xInsetShadowNodeGetColor(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*gdk.RGBA)(unsafe.Pointer(cret))
}

var xInsetShadowNodeGetDx func(uintptr) float32

// Retrieves the horizontal offset of the inset shadow.
func (x *InsetShadowNode) GetDx() float32 {
	cret := xInsetShadowNodeGetDx(x.GoPointer())
	return cret
}

var xInsetShadowNodeGetDy func(uintptr) float32

// Retrieves the vertical offset of the inset shadow.
func (x *InsetShadowNode) GetDy() float32 {
	cret := xInsetShadowNodeGetDy(x.GoPointer())
	return cret
}

var xInsetShadowNodeGetOutline func(uintptr) uintptr

// Retrieves the outline rectangle of the inset shadow.
func (x *InsetShadowNode) GetOutline() *RoundedRect {
	cret := xInsetShadowNodeGetOutline(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*RoundedRect)(unsafe.Pointer(cret))
}

var xInsetShadowNodeGetSpread func(uintptr) float32

// Retrieves how much the shadow spreads inwards.
func (x *InsetShadowNode) GetSpread() float32 {
	cret := xInsetShadowNodeGetSpread(x.GoPointer())
	return cret
}

func (c *InsetShadowNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *InsetShadowNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
	var libs []uintptr
	for _, libPath := range core.GetPaths("GSK") {
		lib, err := purego.Dlopen(libPath, purego.RTLD_NOW|purego.RTLD_GLOBAL)
		if err != nil {
			panic(err)
		}
		libs = append(libs, lib)
	}

	core.PuregoSafeRegister(&xInsetShadowNodeGLibType, libs, "gsk_inset_shadow_node_get_type")

	core.PuregoSafeRegister(&xNewInsetShadowNode, libs, "gsk_inset_shadow_node_new")

	core.PuregoSafeRegister(&xInsetShadowNodeGetBlurRadius, libs, "gsk_inset_shadow_node_get_blur_radius")
	core.PuregoSafeRegister(&xInsetShadowNodeGetColor, libs, "gsk_inset_shadow_node_get_color")
	core.PuregoSafeRegister(&xInsetShadowNodeGetDx, libs, "gsk_inset_shadow_node_get_dx")
	core.PuregoSafeRegister(&xInsetShadowNodeGetDy, libs, "gsk_inset_shadow_node_get_dy")
	core.PuregoSafeRegister(&xInsetShadowNodeGetOutline, libs, "gsk_inset_shadow_node_get_outline")
	core.PuregoSafeRegister(&xInsetShadowNodeGetSpread, libs, "gsk_inset_shadow_node_get_spread")
}
