// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node that isolates its child from surrounding rendernodes.
type IsolationNode struct {
	RenderNode
}

var xIsolationNodeGLibType func() types.GType

func IsolationNodeGLibType() types.GType {
	core.LazyRegister(&xIsolationNodeGLibType, "GSK", "gsk_isolation_node_get_type", false)
	return xIsolationNodeGLibType()
}

func IsolationNodeNewFromInternalPtr(ptr uintptr) *IsolationNode {
	cls := &IsolationNode{}
	cls.Ptr = ptr
	return cls
}

var xNewIsolationNode func(uintptr, Isolation) uintptr

// Creates a `GskRenderNode` that isolates the drawing operations of
// the child from surrounding ones.
//
// You can express "everything but these flags" in a forward compatible
// way by using bit math:
// `GSK_ISOLATION_ALL &amp; ~(GSK_ISOLATION_BACKGROUND | GSK_ISOLATION_COPY_PASTE)`
// will isolate everything but background and copy/paste.
//
// For the available isolations, see [flags@Gsk.Isolation].
func NewIsolationNode(ChildVar *RenderNode, IsolationsVar Isolation) *IsolationNode {
	core.LazyRegister(&xNewIsolationNode, "GSK", "gsk_isolation_node_new", false)
	var cls *IsolationNode

	cret := xNewIsolationNode(ChildVar.GoPointer(), IsolationsVar)

	if cret == 0 {
		return nil
	}
	cls = &IsolationNode{}
	cls.Ptr = cret
	return cls
}

var xIsolationNodeGetChild func(uintptr) uintptr

// Gets the child node that is getting drawn by the given @node.
func (x *IsolationNode) GetChild() *RenderNode {
	core.LazyRegister(&xIsolationNodeGetChild, "GSK", "gsk_isolation_node_get_child", false)
	var cls *RenderNode

	cret := xIsolationNodeGetChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xIsolationNodeGetIsolations func(uintptr) Isolation

// Gets the isolation features that are enforced by this node.
func (x *IsolationNode) GetIsolations() Isolation {
	core.LazyRegister(&xIsolationNodeGetIsolations, "GSK", "gsk_isolation_node_get_isolations", false)

	cret := xIsolationNodeGetIsolations(x.GoPointer())
	return cret
}

func (c *IsolationNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *IsolationNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
