// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"unsafe"

	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
)

// A render node that will fill the area determined by stroking the the given
// [struct@Gsk.Path] using the [struct@Gsk.Stroke] attributes.
type StrokeNode struct {
	RenderNode
}

var xStrokeNodeGLibType func() types.GType

func StrokeNodeGLibType() types.GType {
	core.LazyRegister(&xStrokeNodeGLibType, "GSK", "gsk_stroke_node_get_type", false)
	return xStrokeNodeGLibType()
}

func StrokeNodeNewFromInternalPtr(ptr uintptr) *StrokeNode {
	cls := &StrokeNode{}
	cls.Ptr = ptr
	return cls
}

var xNewStrokeNode func(uintptr, *Path, *Stroke) uintptr

// Creates a #GskRenderNode that will fill the outline generated by stroking
// the given @path using the attributes defined in @stroke.
//
// The area is filled with @child.
//
// GSK aims to follow the SVG semantics for stroking paths.
// E.g. zero-length contours will get round or square line
// caps drawn, regardless whether they are closed or not.
func NewStrokeNode(ChildVar *RenderNode, PathVar *Path, StrokeVar *Stroke) *StrokeNode {
	core.LazyRegister(&xNewStrokeNode, "GSK", "gsk_stroke_node_new", false)
	var cls *StrokeNode

	cret := xNewStrokeNode(ChildVar.GoPointer(), PathVar, StrokeVar)

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &StrokeNode{}
	cls.Ptr = cret
	return cls
}

var xStrokeNodeGetChild func(uintptr) uintptr

// Gets the child node that is getting drawn by the given @node.
func (x *StrokeNode) GetChild() *RenderNode {
	core.LazyRegister(&xStrokeNodeGetChild, "GSK", "gsk_stroke_node_get_child", false)
	var cls *RenderNode

	cret := xStrokeNodeGetChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &RenderNode{}
	cls.Ptr = cret
	return cls
}

var xStrokeNodeGetPath func(uintptr) uintptr

// Retrieves the path that will be stroked with the contents of
// the @node.
func (x *StrokeNode) GetPath() *Path {
	core.LazyRegister(&xStrokeNodeGetPath, "GSK", "gsk_stroke_node_get_path", false)

	cret := xStrokeNodeGetPath(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Path)(unsafe.Pointer(cret))
}

var xStrokeNodeGetStroke func(uintptr) uintptr

// Retrieves the stroke attributes used in this @node.
func (x *StrokeNode) GetStroke() *Stroke {
	core.LazyRegister(&xStrokeNodeGetStroke, "GSK", "gsk_stroke_node_get_stroke", false)

	cret := xStrokeNodeGetStroke(x.GoPointer())
	if cret == 0 {
		return nil
	}
	return (*Stroke)(unsafe.Pointer(cret))
}

func (c *StrokeNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *StrokeNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
