// Package gsk was automatically generated by github.com/bnema/puregotk DO NOT EDIT
package gsk

import (
	"github.com/bnema/puregotk/pkg/core"
	"github.com/bnema/puregotk/v4/gdk"
	"github.com/bnema/puregotk/v4/gobject"
	"github.com/bnema/puregotk/v4/gobject/types"
	"github.com/bnema/puregotk/v4/graphene"
)

// A render node for a `GdkTexture`.
type TextureNode struct {
	RenderNode
}

var xTextureNodeGLibType func() types.GType

func TextureNodeGLibType() types.GType {
	core.LazyRegister(&xTextureNodeGLibType, "GSK", "gsk_texture_node_get_type", false)
	return xTextureNodeGLibType()
}

func TextureNodeNewFromInternalPtr(ptr uintptr) *TextureNode {
	cls := &TextureNode{}
	cls.Ptr = ptr
	return cls
}

var xNewTextureNode func(uintptr, *graphene.Rect) uintptr

// Creates a `GskRenderNode` that will render the given
// @texture into the area given by @bounds.
//
// Note that GSK applies linear filtering when textures are
// scaled and transformed. See [class@Gsk.TextureScaleNode]
// for a way to influence filtering.
func NewTextureNode(TextureVar *gdk.Texture, BoundsVar *graphene.Rect) *TextureNode {
	core.LazyRegister(&xNewTextureNode, "GSK", "gsk_texture_node_new", false)
	var cls *TextureNode

	cret := xNewTextureNode(TextureVar.GoPointer(), BoundsVar)

	if cret == 0 {
		return nil
	}
	cls = &TextureNode{}
	cls.Ptr = cret
	return cls
}

var xTextureNodeGetTexture func(uintptr) uintptr

// Retrieves the `GdkTexture` used when creating this `GskRenderNode`.
func (x *TextureNode) GetTexture() *gdk.Texture {
	core.LazyRegister(&xTextureNodeGetTexture, "GSK", "gsk_texture_node_get_texture", false)
	var cls *gdk.Texture

	cret := xTextureNodeGetTexture(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &gdk.Texture{}
	cls.Ptr = cret
	return cls
}

func (c *TextureNode) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *TextureNode) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	core.SetPackageName("GSK", "gtk4")
	core.SetSharedLibraries("GSK", []string{"libgtk-4.so.1", "libgtk-4.1.dylib"})
}
